// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digger/fountain.proto

package digger

import (
	context1 "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc1 "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	strings "strings"
)

import (
	mservice "git.ezbuy.me/ezbuy/base/dist/mservice"
	ezcommon "git.ezbuy.me/ezbuy/base/dist/proto/common"
	context "git.ezbuy.me/ezbuy/base/misc/context"
	"net/http"
	"sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GDHoldValueIndexListReq struct {
	//
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset"`
	//
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
}

func (m *GDHoldValueIndexListReq) Validate() error {
	return nil
}

func (m *GDHoldValueIndexListReq) Reset()         { *m = GDHoldValueIndexListReq{} }
func (m *GDHoldValueIndexListReq) String() string { return proto.CompactTextString(m) }
func (*GDHoldValueIndexListReq) ProtoMessage()    {}
func (*GDHoldValueIndexListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{0}
}

func (m *GDHoldValueIndexListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GDHoldValueIndexListReq.Unmarshal(m, b)
}
func (m *GDHoldValueIndexListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GDHoldValueIndexListReq.Marshal(b, m, deterministic)
}
func (m *GDHoldValueIndexListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GDHoldValueIndexListReq.Merge(m, src)
}
func (m *GDHoldValueIndexListReq) XXX_Size() int {
	return xxx_messageInfo_GDHoldValueIndexListReq.Size(m)
}
func (m *GDHoldValueIndexListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GDHoldValueIndexListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GDHoldValueIndexListReq proto.InternalMessageInfo

func (m *GDHoldValueIndexListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GDHoldValueIndexListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type HoldValueIndex struct {
	//
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	ValueIndex float32 `protobuf:"fixed32,4,opt,name=valueIndex,proto3" json:"valueIndex"`
	//
	CumulantPrice string `protobuf:"bytes,5,opt,name=cumulantPrice,proto3" json:"cumulantPrice"`
	//
	CumulantFocus string `protobuf:"bytes,6,opt,name=cumulantFocus,proto3" json:"cumulantFocus"`
	//
	CumulantDate string `protobuf:"bytes,7,opt,name=cumulantDate,proto3" json:"cumulantDate"`
	//
	GdreduceRatio string `protobuf:"bytes,8,opt,name=gdreduceRatio,proto3" json:"gdreduceRatio"`
	//
	EndDate string `protobuf:"bytes,9,opt,name=endDate,proto3" json:"endDate"`
	//
	CreateDate int64 `protobuf:"varint,10,opt,name=createDate,proto3" json:"createDate"`
}

func (m *HoldValueIndex) Validate() error {
	return nil
}

func (m *HoldValueIndex) Reset()         { *m = HoldValueIndex{} }
func (m *HoldValueIndex) String() string { return proto.CompactTextString(m) }
func (*HoldValueIndex) ProtoMessage()    {}
func (*HoldValueIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{1}
}

func (m *HoldValueIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldValueIndex.Unmarshal(m, b)
}
func (m *HoldValueIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldValueIndex.Marshal(b, m, deterministic)
}
func (m *HoldValueIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldValueIndex.Merge(m, src)
}
func (m *HoldValueIndex) XXX_Size() int {
	return xxx_messageInfo_HoldValueIndex.Size(m)
}
func (m *HoldValueIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldValueIndex.DiscardUnknown(m)
}

var xxx_messageInfo_HoldValueIndex proto.InternalMessageInfo

func (m *HoldValueIndex) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HoldValueIndex) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *HoldValueIndex) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HoldValueIndex) GetValueIndex() float32 {
	if m != nil {
		return m.ValueIndex
	}
	return 0
}

func (m *HoldValueIndex) GetCumulantPrice() string {
	if m != nil {
		return m.CumulantPrice
	}
	return ""
}

func (m *HoldValueIndex) GetCumulantFocus() string {
	if m != nil {
		return m.CumulantFocus
	}
	return ""
}

func (m *HoldValueIndex) GetCumulantDate() string {
	if m != nil {
		return m.CumulantDate
	}
	return ""
}

func (m *HoldValueIndex) GetGdreduceRatio() string {
	if m != nil {
		return m.GdreduceRatio
	}
	return ""
}

func (m *HoldValueIndex) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *HoldValueIndex) GetCreateDate() int64 {
	if m != nil {
		return m.CreateDate
	}
	return 0
}

type GDHoldValueIndexListResp struct {
	//
	Rows []*HoldValueIndex `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows"`
	//
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (m *GDHoldValueIndexListResp) Validate() error {
	return nil
}

func (m *GDHoldValueIndexListResp) Reset()         { *m = GDHoldValueIndexListResp{} }
func (m *GDHoldValueIndexListResp) String() string { return proto.CompactTextString(m) }
func (*GDHoldValueIndexListResp) ProtoMessage()    {}
func (*GDHoldValueIndexListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{2}
}

func (m *GDHoldValueIndexListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GDHoldValueIndexListResp.Unmarshal(m, b)
}
func (m *GDHoldValueIndexListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GDHoldValueIndexListResp.Marshal(b, m, deterministic)
}
func (m *GDHoldValueIndexListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GDHoldValueIndexListResp.Merge(m, src)
}
func (m *GDHoldValueIndexListResp) XXX_Size() int {
	return xxx_messageInfo_GDHoldValueIndexListResp.Size(m)
}
func (m *GDHoldValueIndexListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GDHoldValueIndexListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GDHoldValueIndexListResp proto.InternalMessageInfo

func (m *GDHoldValueIndexListResp) GetRows() []*HoldValueIndex {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *GDHoldValueIndexListResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GPRecommendListReq struct {
}

func (m *GPRecommendListReq) Validate() error {
	return nil
}

func (m *GPRecommendListReq) Reset()         { *m = GPRecommendListReq{} }
func (m *GPRecommendListReq) String() string { return proto.CompactTextString(m) }
func (*GPRecommendListReq) ProtoMessage()    {}
func (*GPRecommendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{3}
}

func (m *GPRecommendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommendListReq.Unmarshal(m, b)
}
func (m *GPRecommendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommendListReq.Marshal(b, m, deterministic)
}
func (m *GPRecommendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommendListReq.Merge(m, src)
}
func (m *GPRecommendListReq) XXX_Size() int {
	return xxx_messageInfo_GPRecommendListReq.Size(m)
}
func (m *GPRecommendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommendListReq proto.InternalMessageInfo

type GPRecommend struct {
	//
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	RMIndex int32 `protobuf:"varint,4,opt,name=rMIndex,proto3" json:"rMIndex"`
	//
	PDecrease int32 `protobuf:"varint,5,opt,name=pDecrease,proto3" json:"pDecrease"`
	//
	MaxPrice float64 `protobuf:"fixed64,6,opt,name=maxPrice,proto3" json:"maxPrice"`
	//
	MaxPDay string `protobuf:"bytes,10,opt,name=maxPDay,proto3" json:"maxPDay"`
	//
	RMPrice string `protobuf:"bytes,11,opt,name=rMPrice,proto3" json:"rMPrice"`
	//
	GDDecrease int32 `protobuf:"varint,12,opt,name=gDDecrease,proto3" json:"gDDecrease"`
	//
	UpdateDate string `protobuf:"bytes,13,opt,name=updateDate,proto3" json:"updateDate"`
}

func (m *GPRecommend) Validate() error {
	return nil
}

func (m *GPRecommend) Reset()         { *m = GPRecommend{} }
func (m *GPRecommend) String() string { return proto.CompactTextString(m) }
func (*GPRecommend) ProtoMessage()    {}
func (*GPRecommend) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{4}
}

func (m *GPRecommend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommend.Unmarshal(m, b)
}
func (m *GPRecommend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommend.Marshal(b, m, deterministic)
}
func (m *GPRecommend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommend.Merge(m, src)
}
func (m *GPRecommend) XXX_Size() int {
	return xxx_messageInfo_GPRecommend.Size(m)
}
func (m *GPRecommend) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommend.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommend proto.InternalMessageInfo

func (m *GPRecommend) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GPRecommend) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *GPRecommend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPRecommend) GetRMIndex() int32 {
	if m != nil {
		return m.RMIndex
	}
	return 0
}

func (m *GPRecommend) GetPDecrease() int32 {
	if m != nil {
		return m.PDecrease
	}
	return 0
}

func (m *GPRecommend) GetMaxPrice() float64 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *GPRecommend) GetMaxPDay() string {
	if m != nil {
		return m.MaxPDay
	}
	return ""
}

func (m *GPRecommend) GetRMPrice() string {
	if m != nil {
		return m.RMPrice
	}
	return ""
}

func (m *GPRecommend) GetGDDecrease() int32 {
	if m != nil {
		return m.GDDecrease
	}
	return 0
}

func (m *GPRecommend) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

type GPRecommendListResp struct {
	//
	Rows []*GPRecommend `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows"`
	//
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (m *GPRecommendListResp) Validate() error {
	return nil
}

func (m *GPRecommendListResp) Reset()         { *m = GPRecommendListResp{} }
func (m *GPRecommendListResp) String() string { return proto.CompactTextString(m) }
func (*GPRecommendListResp) ProtoMessage()    {}
func (*GPRecommendListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{5}
}

func (m *GPRecommendListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommendListResp.Unmarshal(m, b)
}
func (m *GPRecommendListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommendListResp.Marshal(b, m, deterministic)
}
func (m *GPRecommendListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommendListResp.Merge(m, src)
}
func (m *GPRecommendListResp) XXX_Size() int {
	return xxx_messageInfo_GPRecommendListResp.Size(m)
}
func (m *GPRecommendListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommendListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommendListResp proto.InternalMessageInfo

func (m *GPRecommendListResp) GetRows() []*GPRecommend {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *GPRecommendListResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GDHoldValueIndexListReq)(nil), "digger.GDHoldValueIndexListReq")
	proto.RegisterType((*HoldValueIndex)(nil), "digger.HoldValueIndex")
	proto.RegisterType((*GDHoldValueIndexListResp)(nil), "digger.GDHoldValueIndexListResp")
	proto.RegisterType((*GPRecommendListReq)(nil), "digger.GPRecommendListReq")
	proto.RegisterType((*GPRecommend)(nil), "digger.GPRecommend")
	proto.RegisterType((*GPRecommendListResp)(nil), "digger.GPRecommendListResp")
}

func init() { proto.RegisterFile("digger/fountain.proto", fileDescriptor_a9d02a9263fc9247) }

var fileDescriptor_a9d02a9263fc9247 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0xc6, 0x69, 0xe7, 0x6f, 0xcf, 0xec, 0xae, 0x70, 0x76, 0x5c, 0xc3, 0x28, 0x5a, 0x8a, 0xe0,
	0xe0, 0xc5, 0x2c, 0xac, 0x97, 0xde, 0x49, 0xd9, 0x51, 0x51, 0x58, 0x82, 0x08, 0x8a, 0x37, 0xb1,
	0xc9, 0x0c, 0x85, 0xb6, 0xa9, 0x4d, 0xaa, 0xeb, 0x83, 0xf8, 0x20, 0xbe, 0x81, 0x8f, 0x26, 0x49,
	0xda, 0x6e, 0xab, 0xe3, 0xde, 0x78, 0xd7, 0xef, 0x3b, 0xe7, 0x7c, 0xa7, 0xcd, 0x8f, 0x14, 0xee,
	0xf2, 0x74, 0xbf, 0x17, 0xd5, 0xf9, 0x4e, 0xd6, 0x85, 0x66, 0x69, 0xb1, 0x29, 0x2b, 0xa9, 0x25,
	0x4e, 0x9d, 0x1d, 0x6d, 0xe1, 0xde, 0x36, 0x7e, 0x29, 0x33, 0xfe, 0x9e, 0x65, 0xb5, 0x78, 0x55,
	0x70, 0x71, 0xfd, 0x26, 0x55, 0x9a, 0x8a, 0x2f, 0x78, 0x06, 0x53, 0xb9, 0xdb, 0x29, 0xa1, 0x89,
	0x17, 0x7a, 0xeb, 0x09, 0x6d, 0x14, 0x2e, 0x61, 0x92, 0xa5, 0x79, 0xaa, 0x89, 0x6f, 0x6d, 0x27,
	0xa2, 0x5f, 0x3e, 0x9c, 0x0c, 0x73, 0xf0, 0x04, 0xfc, 0x94, 0x37, 0xc3, 0x7e, 0xca, 0x71, 0x05,
	0x73, 0x25, 0x92, 0x3a, 0x91, 0x5c, 0xd8, 0xd9, 0x80, 0x76, 0x1a, 0x11, 0xc6, 0x05, 0xcb, 0x05,
	0x19, 0x59, 0xdf, 0x3e, 0xe3, 0x43, 0x80, 0xaf, 0x5d, 0x1a, 0x19, 0x87, 0xde, 0xda, 0xa7, 0x3d,
	0x07, 0x1f, 0xc3, 0x71, 0x52, 0xe7, 0x75, 0xc6, 0x0a, 0x7d, 0x55, 0xa5, 0x89, 0x20, 0x13, 0x3b,
	0x3c, 0x34, 0xfb, 0x5d, 0x97, 0x32, 0xa9, 0x15, 0x99, 0x0e, 0xbb, 0xac, 0x89, 0x11, 0x1c, 0xb5,
	0x46, 0xcc, 0xb4, 0x20, 0x33, 0xdb, 0x34, 0xf0, 0x4c, 0xd2, 0x9e, 0x57, 0x82, 0xd7, 0x89, 0xa0,
	0x4c, 0xa7, 0x92, 0xcc, 0x5d, 0xd2, 0xc0, 0x44, 0x02, 0x33, 0x51, 0x70, 0x1b, 0x12, 0xd8, 0x7a,
	0x2b, 0xcd, 0xf7, 0x24, 0x95, 0x60, 0x5a, 0xd8, 0x22, 0x84, 0xde, 0x7a, 0x44, 0x7b, 0x4e, 0xf4,
	0x09, 0xc8, 0x61, 0x16, 0xaa, 0xc4, 0xa7, 0x30, 0xae, 0xe4, 0x37, 0x45, 0xbc, 0x70, 0xb4, 0x5e,
	0x5c, 0x9c, 0x6d, 0x1c, 0xbe, 0xcd, 0xb0, 0x9b, 0xda, 0x1e, 0x03, 0x48, 0x4b, 0xcd, 0xb2, 0x16,
	0x90, 0x15, 0xd1, 0x12, 0x70, 0x7b, 0x45, 0x45, 0x22, 0xf3, 0x5c, 0x14, 0xbc, 0x81, 0x1c, 0xfd,
	0xf0, 0x61, 0xd1, 0xb3, 0xff, 0x9b, 0x19, 0x81, 0x59, 0xf5, 0xf6, 0x06, 0xd8, 0x84, 0xb6, 0x12,
	0x1f, 0x40, 0x50, 0xc6, 0xc2, 0x7c, 0xae, 0x72, 0xa4, 0x26, 0xf4, 0xc6, 0x30, 0x7b, 0x72, 0x76,
	0xed, 0x30, 0x1a, 0x40, 0x1e, 0xed, 0xb4, 0xc9, 0x34, 0xcf, 0x31, 0xfb, 0x6e, 0x0f, 0x2d, 0xa0,
	0xad, 0x74, 0xdb, 0xdc, 0xd0, 0xc2, 0x55, 0x1a, 0x69, 0xce, 0x7a, 0x1f, 0x77, 0xeb, 0x8e, 0xec,
	0xba, 0x9e, 0x63, 0xea, 0x75, 0xc9, 0x5b, 0x16, 0xc7, 0x76, 0xb8, 0xe7, 0x44, 0xef, 0xe0, 0xf4,
	0xaf, 0xd3, 0x52, 0x25, 0x3e, 0x19, 0x60, 0x38, 0x6d, 0x31, 0xf4, 0x5a, 0x6f, 0x63, 0x70, 0xf1,
	0xd3, 0x83, 0xf9, 0x65, 0x73, 0x11, 0xf1, 0x03, 0x2c, 0x0f, 0xe1, 0xc6, 0x47, 0x5d, 0xea, 0xe1,
	0x8b, 0xb9, 0x0a, 0x6f, 0x6f, 0x50, 0x25, 0xbe, 0x86, 0x3b, 0x7f, 0xbc, 0x3d, 0xae, 0x0e, 0xbc,
	0x6b, 0x1b, 0x78, 0xff, 0x9f, 0x35, 0x55, 0xbe, 0x58, 0x7c, 0x0c, 0x36, 0xe7, 0xcf, 0x5d, 0xc3,
	0xe7, 0xa9, 0xfd, 0x7b, 0x3c, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x54, 0x36, 0x49, 0xcc, 0x56,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn
var _ http.Client
var _ ezcommon.Empty

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion6

const ServiceFountain = "digger.Fountain"

var ServiceMethodFountain = []string{
	"GDHoldValueIndexList",
	"GPRecommendList",
}

// Client API for Fountain service

// FountainClient is the client API for Fountain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FountainClient interface {
	GDHoldValueIndexList(ctx context.T, in *GDHoldValueIndexListReq, opts ...grpc1.CallOption) (*GDHoldValueIndexListResp, error)
	GPRecommendList(ctx context.T, in *GPRecommendListReq, opts ...grpc1.CallOption) (*GPRecommendListResp, error)
}

type fountainClient struct {
	cc *grpc1.ClientConn
}

var fountainClientOnce sync.Once
var fountainClientInstance FountainClient

func GetFountain() FountainClient {
	fountainClientOnce.Do(func() {
		var err error
		fountainClientInstance, err = NewFountain()
		if err != nil {
			panic(err)
		}
	})
	return fountainClientInstance
}

func NewFountain() (FountainClient, error) {
	cfg := mservice.DefaultClientConfig()
	cfg.Desc = OptionFountain
	cli, err := mservice.NewClientEx(ServiceFountain, cfg)
	if err != nil {
		return nil, err
	}
	return NewFountainClient(cli.GRPC), nil
}

func NewFountainClient(cc *grpc1.ClientConn) FountainClient {
	return &fountainClient{cc}
}

func (c *fountainClient) GDHoldValueIndexList(ctx context.T, in *GDHoldValueIndexListReq, opts ...grpc1.CallOption) (*GDHoldValueIndexListResp, error) {
	out := new(GDHoldValueIndexListResp)
	err := c.cc.Invoke(ctx, "/digger.Fountain/GDHoldValueIndexList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fountainClient) GPRecommendList(ctx context.T, in *GPRecommendListReq, opts ...grpc1.CallOption) (*GPRecommendListResp, error) {
	out := new(GPRecommendListResp)
	err := c.cc.Invoke(ctx, "/digger.Fountain/GPRecommendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FountainServer is the server API for Fountain service.
type FountainServer interface {
	GDHoldValueIndexList(context.T, *GDHoldValueIndexListReq) (*GDHoldValueIndexListResp, error)
	GPRecommendList(context.T, *GPRecommendListReq) (*GPRecommendListResp, error)
}

func RegisterFountainGrpc(s FountainGrpcRegister) {
	s.RegisterService(ServiceFountain, ServiceMethodFountain)
	RegisterFountainServer(s.GetServer(), s)
}

func RegisterFountainGrpcImpl(s mservice.GrpcRegister, impl FountainServer) {
	s.RegisterService(ServiceFountain, ServiceMethodFountain)
	RegisterFountainServer(s.GetServer(), impl)
}

// UnimplementedFountainServer can be embedded to have forward compatible implementations.
type UnimplementedFountainServer struct {
}

func (*UnimplementedFountainServer) GDHoldValueIndexList(ctx context1.Context, req *GDHoldValueIndexListReq) (*GDHoldValueIndexListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GDHoldValueIndexList not implemented")
}
func (*UnimplementedFountainServer) GPRecommendList(ctx context1.Context, req *GPRecommendListReq) (*GPRecommendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GPRecommendList not implemented")
}

func RegisterFountainServer(s *grpc1.Server, srv FountainServer) {
	s.RegisterService(&_Fountain_serviceDesc, srv)
}

type FountainMServicer interface {
	RegisterServiceDesc(*ezcommon.ServiceOpDesc)
	FountainServer
	mservice.WebApiRegister
	mservice.GrpcRegister
	mservice.WebSocketRegister
}

type FountainGrpcRegister interface {
	FountainServer
	mservice.GrpcRegister
}

func RegisterFountain(s FountainMServicer) {
	s.RegisterServiceDesc(OptionFountain)
	RegisterFountainGrpc(s)
	RegisterFountainWebapiEx(s)
	RegisterFountainWebSocket(s)
}

type FountainWebApiRegister interface {
	FountainServer
	mservice.WebApiRegister
}

func RegisterFountainWebApi(s FountainWebApiRegister) {
	RegisterFountainWebApiImpl(s, s)
}

func RegisterFountainWebApiImpl(s mservice.WebApiRegister, impl FountainServer) {
	wrap := &FountainWebapi{server: impl, register: s}
	_ = wrap
	s.WebApiRegister("/api/digger.Fountain/GDHoldValueIndexList", wrap.GDHoldValueIndexList)
	s.WebApiRegister("/api/digger.Fountain/GPRecommendList", wrap.GPRecommendList)
}

func RegisterFountainWebapiEx(s FountainWebApiRegister) {
	wrap := &FountainWebapi{server: s, register: s}
	_ = wrap
	s.WebApiRegisterMethod("digger.Fountain", "GDHoldValueIndexList", wrap.GDHoldValueIndexList)
	s.WebApiRegisterMethod("digger.Fountain", "GPRecommendList", wrap.GPRecommendList)
}

type FountainWebapi struct {
	server   FountainServer
	register mservice.WebApiRegister
}

func (s *FountainWebapi) GDHoldValueIndexList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GDHoldValueIndexListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GDHoldValueIndexList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *FountainWebapi) GPRecommendList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GPRecommendListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GPRecommendList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

type FountainWebSocketApi interface {
}

type FountainWebSocketRegister interface {
	FountainWebSocketApi
	mservice.WebSocketRegister
}

func RegisterFountainWebSocket(s FountainWebSocketRegister) {
}

type FountainWebSocket struct {
	api      FountainWebSocketApi
	register mservice.WebSocketRegister
}

func _Fountain_GDHoldValueIndexList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GDHoldValueIndexListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FountainServer).GDHoldValueIndexList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.Fountain/GDHoldValueIndexList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(FountainServer).GDHoldValueIndexList(context.From(ctx), req.(*GDHoldValueIndexListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fountain_GPRecommendList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPRecommendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FountainServer).GPRecommendList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.Fountain/GPRecommendList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(FountainServer).GPRecommendList(context.From(ctx), req.(*GPRecommendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fountain_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "digger.Fountain",
	HandlerType: (*FountainServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GDHoldValueIndexList",
			Handler:    _Fountain_GDHoldValueIndexList_Handler,
		},
		{
			MethodName: "GPRecommendList",
			Handler:    _Fountain_GPRecommendList_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "digger/fountain.proto",
}

var OptionFountain = ezcommon.GenOption([]byte{
	// 60 bytes of Option
	0x0a, 0x0f, 0x64, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x1a, 0x16, 0x0a, 0x14, 0x47, 0x44, 0x48, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x11, 0x0a, 0x0f, 0x47, 0x50, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
})
