// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digger/zwadmin.proto

package digger

import (
	context1 "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc1 "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	strings "strings"
)

import (
	mservice "git.ezbuy.me/ezbuy/base/dist/mservice"
	ezcommon "git.ezbuy.me/ezbuy/base/dist/proto/common"
	context "git.ezbuy.me/ezbuy/base/misc/context"
	"net/http"
	"sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetLongLineListReq struct {
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	GdRatio int32 `protobuf:"varint,3,opt,name=gdRatio,proto3" json:"gdRatio"`
	//
	Limit int32 `protobuf:"varint,10,opt,name=limit,proto3" json:"limit"`
	//
	Offset int32 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset"`
}

func (m *GetLongLineListReq) Validate() error {
	return nil
}

func (m *GetLongLineListReq) Reset()         { *m = GetLongLineListReq{} }
func (m *GetLongLineListReq) String() string { return proto.CompactTextString(m) }
func (*GetLongLineListReq) ProtoMessage()    {}
func (*GetLongLineListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{0}
}

func (m *GetLongLineListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLongLineListReq.Unmarshal(m, b)
}
func (m *GetLongLineListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLongLineListReq.Marshal(b, m, deterministic)
}
func (m *GetLongLineListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLongLineListReq.Merge(m, src)
}
func (m *GetLongLineListReq) XXX_Size() int {
	return xxx_messageInfo_GetLongLineListReq.Size(m)
}
func (m *GetLongLineListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLongLineListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLongLineListReq proto.InternalMessageInfo

func (m *GetLongLineListReq) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *GetLongLineListReq) GetGdRatio() int32 {
	if m != nil {
		return m.GdRatio
	}
	return 0
}

func (m *GetLongLineListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetLongLineListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type LongLineItem struct {
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	Price string `protobuf:"bytes,4,opt,name=price,proto3" json:"price"`
	//
	Focus string `protobuf:"bytes,5,opt,name=focus,proto3" json:"focus"`
	//
	Date string `protobuf:"bytes,6,opt,name=date,proto3" json:"date"`
	//
	RatioStr string `protobuf:"bytes,7,opt,name=ratioStr,proto3" json:"ratioStr"`
	//
	GdRatio int32 `protobuf:"varint,8,opt,name=gdRatio,proto3" json:"gdRatio"`
	//
	CreateDate string `protobuf:"bytes,9,opt,name=createDate,proto3" json:"createDate"`
	//
	PresentPrice float64 `protobuf:"fixed64,10,opt,name=presentPrice,proto3" json:"presentPrice"`
	//
	ValueIndex int32 `protobuf:"varint,11,opt,name=valueIndex,proto3" json:"valueIndex"`
}

func (m *LongLineItem) Validate() error {
	return nil
}

func (m *LongLineItem) Reset()         { *m = LongLineItem{} }
func (m *LongLineItem) String() string { return proto.CompactTextString(m) }
func (*LongLineItem) ProtoMessage()    {}
func (*LongLineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{1}
}

func (m *LongLineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongLineItem.Unmarshal(m, b)
}
func (m *LongLineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongLineItem.Marshal(b, m, deterministic)
}
func (m *LongLineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongLineItem.Merge(m, src)
}
func (m *LongLineItem) XXX_Size() int {
	return xxx_messageInfo_LongLineItem.Size(m)
}
func (m *LongLineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LongLineItem.DiscardUnknown(m)
}

var xxx_messageInfo_LongLineItem proto.InternalMessageInfo

func (m *LongLineItem) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *LongLineItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LongLineItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *LongLineItem) GetFocus() string {
	if m != nil {
		return m.Focus
	}
	return ""
}

func (m *LongLineItem) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *LongLineItem) GetRatioStr() string {
	if m != nil {
		return m.RatioStr
	}
	return ""
}

func (m *LongLineItem) GetGdRatio() int32 {
	if m != nil {
		return m.GdRatio
	}
	return 0
}

func (m *LongLineItem) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *LongLineItem) GetPresentPrice() float64 {
	if m != nil {
		return m.PresentPrice
	}
	return 0
}

func (m *LongLineItem) GetValueIndex() int32 {
	if m != nil {
		return m.ValueIndex
	}
	return 0
}

type LongLineData struct {
	//
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	//
	Items []*LongLineItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (m *LongLineData) Validate() error {
	return nil
}

func (m *LongLineData) Reset()         { *m = LongLineData{} }
func (m *LongLineData) String() string { return proto.CompactTextString(m) }
func (*LongLineData) ProtoMessage()    {}
func (*LongLineData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{2}
}

func (m *LongLineData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongLineData.Unmarshal(m, b)
}
func (m *LongLineData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongLineData.Marshal(b, m, deterministic)
}
func (m *LongLineData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongLineData.Merge(m, src)
}
func (m *LongLineData) XXX_Size() int {
	return xxx_messageInfo_LongLineData.Size(m)
}
func (m *LongLineData) XXX_DiscardUnknown() {
	xxx_messageInfo_LongLineData.DiscardUnknown(m)
}

var xxx_messageInfo_LongLineData proto.InternalMessageInfo

func (m *LongLineData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *LongLineData) GetItems() []*LongLineItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetLongLineListResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *LongLineData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *GetLongLineListResp) Validate() error {
	return nil
}

func (m *GetLongLineListResp) Reset()         { *m = GetLongLineListResp{} }
func (m *GetLongLineListResp) String() string { return proto.CompactTextString(m) }
func (*GetLongLineListResp) ProtoMessage()    {}
func (*GetLongLineListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{3}
}

func (m *GetLongLineListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLongLineListResp.Unmarshal(m, b)
}
func (m *GetLongLineListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLongLineListResp.Marshal(b, m, deterministic)
}
func (m *GetLongLineListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLongLineListResp.Merge(m, src)
}
func (m *GetLongLineListResp) XXX_Size() int {
	return xxx_messageInfo_GetLongLineListResp.Size(m)
}
func (m *GetLongLineListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLongLineListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLongLineListResp proto.InternalMessageInfo

func (m *GetLongLineListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetLongLineListResp) GetData() *LongLineData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PromptBuyListReq struct {
	//
	Limit int32 `protobuf:"varint,10,opt,name=limit,proto3" json:"limit"`
	//
	Offset int32 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset"`
}

func (m *PromptBuyListReq) Validate() error {
	return nil
}

func (m *PromptBuyListReq) Reset()         { *m = PromptBuyListReq{} }
func (m *PromptBuyListReq) String() string { return proto.CompactTextString(m) }
func (*PromptBuyListReq) ProtoMessage()    {}
func (*PromptBuyListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{4}
}

func (m *PromptBuyListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptBuyListReq.Unmarshal(m, b)
}
func (m *PromptBuyListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptBuyListReq.Marshal(b, m, deterministic)
}
func (m *PromptBuyListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptBuyListReq.Merge(m, src)
}
func (m *PromptBuyListReq) XXX_Size() int {
	return xxx_messageInfo_PromptBuyListReq.Size(m)
}
func (m *PromptBuyListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptBuyListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PromptBuyListReq proto.InternalMessageInfo

func (m *PromptBuyListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PromptBuyListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PromptBuyItem struct {
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	MinPrice float64 `protobuf:"fixed64,4,opt,name=minPrice,proto3" json:"minPrice"`
	//
	PresentPrice float64 `protobuf:"fixed64,5,opt,name=presentPrice,proto3" json:"presentPrice"`
	//
	PriceDiff float64 `protobuf:"fixed64,6,opt,name=priceDiff,proto3" json:"priceDiff"`
	//
	CreateDate string `protobuf:"bytes,7,opt,name=createDate,proto3" json:"createDate"`
}

func (m *PromptBuyItem) Validate() error {
	return nil
}

func (m *PromptBuyItem) Reset()         { *m = PromptBuyItem{} }
func (m *PromptBuyItem) String() string { return proto.CompactTextString(m) }
func (*PromptBuyItem) ProtoMessage()    {}
func (*PromptBuyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{5}
}

func (m *PromptBuyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptBuyItem.Unmarshal(m, b)
}
func (m *PromptBuyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptBuyItem.Marshal(b, m, deterministic)
}
func (m *PromptBuyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptBuyItem.Merge(m, src)
}
func (m *PromptBuyItem) XXX_Size() int {
	return xxx_messageInfo_PromptBuyItem.Size(m)
}
func (m *PromptBuyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptBuyItem.DiscardUnknown(m)
}

var xxx_messageInfo_PromptBuyItem proto.InternalMessageInfo

func (m *PromptBuyItem) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *PromptBuyItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PromptBuyItem) GetMinPrice() float64 {
	if m != nil {
		return m.MinPrice
	}
	return 0
}

func (m *PromptBuyItem) GetPresentPrice() float64 {
	if m != nil {
		return m.PresentPrice
	}
	return 0
}

func (m *PromptBuyItem) GetPriceDiff() float64 {
	if m != nil {
		return m.PriceDiff
	}
	return 0
}

func (m *PromptBuyItem) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

type PromptBuyData struct {
	//
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	//
	Items []*PromptBuyItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (m *PromptBuyData) Validate() error {
	return nil
}

func (m *PromptBuyData) Reset()         { *m = PromptBuyData{} }
func (m *PromptBuyData) String() string { return proto.CompactTextString(m) }
func (*PromptBuyData) ProtoMessage()    {}
func (*PromptBuyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{6}
}

func (m *PromptBuyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptBuyData.Unmarshal(m, b)
}
func (m *PromptBuyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptBuyData.Marshal(b, m, deterministic)
}
func (m *PromptBuyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptBuyData.Merge(m, src)
}
func (m *PromptBuyData) XXX_Size() int {
	return xxx_messageInfo_PromptBuyData.Size(m)
}
func (m *PromptBuyData) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptBuyData.DiscardUnknown(m)
}

var xxx_messageInfo_PromptBuyData proto.InternalMessageInfo

func (m *PromptBuyData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PromptBuyData) GetItems() []*PromptBuyItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type PromptBuyListResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *PromptBuyData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *PromptBuyListResp) Validate() error {
	return nil
}

func (m *PromptBuyListResp) Reset()         { *m = PromptBuyListResp{} }
func (m *PromptBuyListResp) String() string { return proto.CompactTextString(m) }
func (*PromptBuyListResp) ProtoMessage()    {}
func (*PromptBuyListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{7}
}

func (m *PromptBuyListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptBuyListResp.Unmarshal(m, b)
}
func (m *PromptBuyListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptBuyListResp.Marshal(b, m, deterministic)
}
func (m *PromptBuyListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptBuyListResp.Merge(m, src)
}
func (m *PromptBuyListResp) XXX_Size() int {
	return xxx_messageInfo_PromptBuyListResp.Size(m)
}
func (m *PromptBuyListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptBuyListResp.DiscardUnknown(m)
}

var xxx_messageInfo_PromptBuyListResp proto.InternalMessageInfo

func (m *PromptBuyListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PromptBuyListResp) GetData() *PromptBuyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePromptBuyReq struct {
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Disabled bool `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled"`
}

func (m *UpdatePromptBuyReq) Validate() error {
	return nil
}

func (m *UpdatePromptBuyReq) Reset()         { *m = UpdatePromptBuyReq{} }
func (m *UpdatePromptBuyReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePromptBuyReq) ProtoMessage()    {}
func (*UpdatePromptBuyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{8}
}

func (m *UpdatePromptBuyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePromptBuyReq.Unmarshal(m, b)
}
func (m *UpdatePromptBuyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePromptBuyReq.Marshal(b, m, deterministic)
}
func (m *UpdatePromptBuyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePromptBuyReq.Merge(m, src)
}
func (m *UpdatePromptBuyReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePromptBuyReq.Size(m)
}
func (m *UpdatePromptBuyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePromptBuyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePromptBuyReq proto.InternalMessageInfo

func (m *UpdatePromptBuyReq) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *UpdatePromptBuyReq) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type UpdatePromptBuyResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
}

func (m *UpdatePromptBuyResp) Validate() error {
	return nil
}

func (m *UpdatePromptBuyResp) Reset()         { *m = UpdatePromptBuyResp{} }
func (m *UpdatePromptBuyResp) String() string { return proto.CompactTextString(m) }
func (*UpdatePromptBuyResp) ProtoMessage()    {}
func (*UpdatePromptBuyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{9}
}

func (m *UpdatePromptBuyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePromptBuyResp.Unmarshal(m, b)
}
func (m *UpdatePromptBuyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePromptBuyResp.Marshal(b, m, deterministic)
}
func (m *UpdatePromptBuyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePromptBuyResp.Merge(m, src)
}
func (m *UpdatePromptBuyResp) XXX_Size() int {
	return xxx_messageInfo_UpdatePromptBuyResp.Size(m)
}
func (m *UpdatePromptBuyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePromptBuyResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePromptBuyResp proto.InternalMessageInfo

func (m *UpdatePromptBuyResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UpdateRecommendReq struct {
	//
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	PriceDecrease int32 `protobuf:"varint,3,opt,name=priceDecrease,proto3" json:"priceDecrease"`
}

func (m *UpdateRecommendReq) Validate() error {
	return nil
}

func (m *UpdateRecommendReq) Reset()         { *m = UpdateRecommendReq{} }
func (m *UpdateRecommendReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRecommendReq) ProtoMessage()    {}
func (*UpdateRecommendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{10}
}

func (m *UpdateRecommendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecommendReq.Unmarshal(m, b)
}
func (m *UpdateRecommendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecommendReq.Marshal(b, m, deterministic)
}
func (m *UpdateRecommendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecommendReq.Merge(m, src)
}
func (m *UpdateRecommendReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRecommendReq.Size(m)
}
func (m *UpdateRecommendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecommendReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecommendReq proto.InternalMessageInfo

func (m *UpdateRecommendReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRecommendReq) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *UpdateRecommendReq) GetPriceDecrease() int32 {
	if m != nil {
		return m.PriceDecrease
	}
	return 0
}

type UpdateRecommendResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
}

func (m *UpdateRecommendResp) Validate() error {
	return nil
}

func (m *UpdateRecommendResp) Reset()         { *m = UpdateRecommendResp{} }
func (m *UpdateRecommendResp) String() string { return proto.CompactTextString(m) }
func (*UpdateRecommendResp) ProtoMessage()    {}
func (*UpdateRecommendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{11}
}

func (m *UpdateRecommendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecommendResp.Unmarshal(m, b)
}
func (m *UpdateRecommendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecommendResp.Marshal(b, m, deterministic)
}
func (m *UpdateRecommendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecommendResp.Merge(m, src)
}
func (m *UpdateRecommendResp) XXX_Size() int {
	return xxx_messageInfo_UpdateRecommendResp.Size(m)
}
func (m *UpdateRecommendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecommendResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecommendResp proto.InternalMessageInfo

func (m *UpdateRecommendResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GetRecommendReq struct {
	//
	PDecrease int32 `protobuf:"varint,1,opt,name=pDecrease,proto3" json:"pDecrease"`
	//
	State int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state"`
	//
	Secucode string `protobuf:"bytes,3,opt,name=secucode,proto3" json:"secucode"`
	//
	Limit int32 `protobuf:"varint,10,opt,name=limit,proto3" json:"limit"`
	//
	Offset int32 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset"`
}

func (m *GetRecommendReq) Validate() error {
	return nil
}

func (m *GetRecommendReq) Reset()         { *m = GetRecommendReq{} }
func (m *GetRecommendReq) String() string { return proto.CompactTextString(m) }
func (*GetRecommendReq) ProtoMessage()    {}
func (*GetRecommendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{12}
}

func (m *GetRecommendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendReq.Unmarshal(m, b)
}
func (m *GetRecommendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendReq.Marshal(b, m, deterministic)
}
func (m *GetRecommendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendReq.Merge(m, src)
}
func (m *GetRecommendReq) XXX_Size() int {
	return xxx_messageInfo_GetRecommendReq.Size(m)
}
func (m *GetRecommendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendReq proto.InternalMessageInfo

func (m *GetRecommendReq) GetPDecrease() int32 {
	if m != nil {
		return m.PDecrease
	}
	return 0
}

func (m *GetRecommendReq) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GetRecommendReq) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *GetRecommendReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRecommendReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type RecommendItem struct {
	//
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	RMIndex int32 `protobuf:"varint,4,opt,name=rMIndex,proto3" json:"rMIndex"`
	//
	PDecrease int32 `protobuf:"varint,5,opt,name=pDecrease,proto3" json:"pDecrease"`
	//
	MaxPrice float64 `protobuf:"fixed64,6,opt,name=maxPrice,proto3" json:"maxPrice"`
	//
	MaxPDay string `protobuf:"bytes,10,opt,name=maxPDay,proto3" json:"maxPDay"`
	//
	RMPrice string `protobuf:"bytes,11,opt,name=rMPrice,proto3" json:"rMPrice"`
	//
	GDDecrease int32 `protobuf:"varint,12,opt,name=gDDecrease,proto3" json:"gDDecrease"`
	//
	State string `protobuf:"bytes,13,opt,name=state,proto3" json:"state"`
	//
	UpdateNum int32 `protobuf:"varint,14,opt,name=updateNum,proto3" json:"updateNum"`
	//
	ReferDecrease int32 `protobuf:"varint,15,opt,name=referDecrease,proto3" json:"referDecrease"`
	//
	UpdateDate string `protobuf:"bytes,16,opt,name=updateDate,proto3" json:"updateDate"`
	//
	PresentPrice float64 `protobuf:"fixed64,17,opt,name=presentPrice,proto3" json:"presentPrice"`
}

func (m *RecommendItem) Validate() error {
	return nil
}

func (m *RecommendItem) Reset()         { *m = RecommendItem{} }
func (m *RecommendItem) String() string { return proto.CompactTextString(m) }
func (*RecommendItem) ProtoMessage()    {}
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{13}
}

func (m *RecommendItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendItem.Unmarshal(m, b)
}
func (m *RecommendItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendItem.Marshal(b, m, deterministic)
}
func (m *RecommendItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendItem.Merge(m, src)
}
func (m *RecommendItem) XXX_Size() int {
	return xxx_messageInfo_RecommendItem.Size(m)
}
func (m *RecommendItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendItem proto.InternalMessageInfo

func (m *RecommendItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RecommendItem) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *RecommendItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecommendItem) GetRMIndex() int32 {
	if m != nil {
		return m.RMIndex
	}
	return 0
}

func (m *RecommendItem) GetPDecrease() int32 {
	if m != nil {
		return m.PDecrease
	}
	return 0
}

func (m *RecommendItem) GetMaxPrice() float64 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *RecommendItem) GetMaxPDay() string {
	if m != nil {
		return m.MaxPDay
	}
	return ""
}

func (m *RecommendItem) GetRMPrice() string {
	if m != nil {
		return m.RMPrice
	}
	return ""
}

func (m *RecommendItem) GetGDDecrease() int32 {
	if m != nil {
		return m.GDDecrease
	}
	return 0
}

func (m *RecommendItem) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *RecommendItem) GetUpdateNum() int32 {
	if m != nil {
		return m.UpdateNum
	}
	return 0
}

func (m *RecommendItem) GetReferDecrease() int32 {
	if m != nil {
		return m.ReferDecrease
	}
	return 0
}

func (m *RecommendItem) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

func (m *RecommendItem) GetPresentPrice() float64 {
	if m != nil {
		return m.PresentPrice
	}
	return 0
}

type RecommendData struct {
	//
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	//
	Items []*RecommendItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
}

func (m *RecommendData) Validate() error {
	return nil
}

func (m *RecommendData) Reset()         { *m = RecommendData{} }
func (m *RecommendData) String() string { return proto.CompactTextString(m) }
func (*RecommendData) ProtoMessage()    {}
func (*RecommendData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{14}
}

func (m *RecommendData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendData.Unmarshal(m, b)
}
func (m *RecommendData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendData.Marshal(b, m, deterministic)
}
func (m *RecommendData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendData.Merge(m, src)
}
func (m *RecommendData) XXX_Size() int {
	return xxx_messageInfo_RecommendData.Size(m)
}
func (m *RecommendData) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendData.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendData proto.InternalMessageInfo

func (m *RecommendData) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RecommendData) GetItems() []*RecommendItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetRecommendResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *RecommendData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *GetRecommendResp) Validate() error {
	return nil
}

func (m *GetRecommendResp) Reset()         { *m = GetRecommendResp{} }
func (m *GetRecommendResp) String() string { return proto.CompactTextString(m) }
func (*GetRecommendResp) ProtoMessage()    {}
func (*GetRecommendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{15}
}

func (m *GetRecommendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendResp.Unmarshal(m, b)
}
func (m *GetRecommendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendResp.Marshal(b, m, deterministic)
}
func (m *GetRecommendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendResp.Merge(m, src)
}
func (m *GetRecommendResp) XXX_Size() int {
	return xxx_messageInfo_GetRecommendResp.Size(m)
}
func (m *GetRecommendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendResp proto.InternalMessageInfo

func (m *GetRecommendResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRecommendResp) GetData() *RecommendData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserLogoutReq struct {
}

func (m *UserLogoutReq) Validate() error {
	return nil
}

func (m *UserLogoutReq) Reset()         { *m = UserLogoutReq{} }
func (m *UserLogoutReq) String() string { return proto.CompactTextString(m) }
func (*UserLogoutReq) ProtoMessage()    {}
func (*UserLogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{16}
}

func (m *UserLogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutReq.Unmarshal(m, b)
}
func (m *UserLogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutReq.Marshal(b, m, deterministic)
}
func (m *UserLogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutReq.Merge(m, src)
}
func (m *UserLogoutReq) XXX_Size() int {
	return xxx_messageInfo_UserLogoutReq.Size(m)
}
func (m *UserLogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutReq proto.InternalMessageInfo

type UserLogoutResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
}

func (m *UserLogoutResp) Validate() error {
	return nil
}

func (m *UserLogoutResp) Reset()         { *m = UserLogoutResp{} }
func (m *UserLogoutResp) String() string { return proto.CompactTextString(m) }
func (*UserLogoutResp) ProtoMessage()    {}
func (*UserLogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{17}
}

func (m *UserLogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutResp.Unmarshal(m, b)
}
func (m *UserLogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutResp.Marshal(b, m, deterministic)
}
func (m *UserLogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutResp.Merge(m, src)
}
func (m *UserLogoutResp) XXX_Size() int {
	return xxx_messageInfo_UserLogoutResp.Size(m)
}
func (m *UserLogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutResp proto.InternalMessageInfo

func (m *UserLogoutResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UserInfoData struct {
	//
	Avatar string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar"`
	//
	Introduction string `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	Roles []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles"`
}

func (m *UserInfoData) Validate() error {
	return nil
}

func (m *UserInfoData) Reset()         { *m = UserInfoData{} }
func (m *UserInfoData) String() string { return proto.CompactTextString(m) }
func (*UserInfoData) ProtoMessage()    {}
func (*UserInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{18}
}

func (m *UserInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoData.Unmarshal(m, b)
}
func (m *UserInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoData.Marshal(b, m, deterministic)
}
func (m *UserInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoData.Merge(m, src)
}
func (m *UserInfoData) XXX_Size() int {
	return xxx_messageInfo_UserInfoData.Size(m)
}
func (m *UserInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoData proto.InternalMessageInfo

func (m *UserInfoData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfoData) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UserInfoData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfoData) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserInfoReq struct {
}

func (m *UserInfoReq) Validate() error {
	return nil
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{19}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

type UserInfoResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *UserInfoData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *UserInfoResp) Validate() error {
	return nil
}

func (m *UserInfoResp) Reset()         { *m = UserInfoResp{} }
func (m *UserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoResp) ProtoMessage()    {}
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{20}
}

func (m *UserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResp.Unmarshal(m, b)
}
func (m *UserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResp.Marshal(b, m, deterministic)
}
func (m *UserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResp.Merge(m, src)
}
func (m *UserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoResp.Size(m)
}
func (m *UserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResp proto.InternalMessageInfo

func (m *UserInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResp) GetData() *UserInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserLoginReq struct {
	//
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username"`
	//
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
}

func (m *UserLoginReq) Validate() error {
	return nil
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{21}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginData struct {
	//
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
}

func (m *LoginData) Validate() error {
	return nil
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{22}
}

func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (m *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(m, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserLoginResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *LoginData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *UserLoginResp) Validate() error {
	return nil
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{23}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserLoginResp) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLongLineListReq)(nil), "digger.GetLongLineListReq")
	proto.RegisterType((*LongLineItem)(nil), "digger.LongLineItem")
	proto.RegisterType((*LongLineData)(nil), "digger.LongLineData")
	proto.RegisterType((*GetLongLineListResp)(nil), "digger.GetLongLineListResp")
	proto.RegisterType((*PromptBuyListReq)(nil), "digger.PromptBuyListReq")
	proto.RegisterType((*PromptBuyItem)(nil), "digger.PromptBuyItem")
	proto.RegisterType((*PromptBuyData)(nil), "digger.PromptBuyData")
	proto.RegisterType((*PromptBuyListResp)(nil), "digger.PromptBuyListResp")
	proto.RegisterType((*UpdatePromptBuyReq)(nil), "digger.UpdatePromptBuyReq")
	proto.RegisterType((*UpdatePromptBuyResp)(nil), "digger.UpdatePromptBuyResp")
	proto.RegisterType((*UpdateRecommendReq)(nil), "digger.UpdateRecommendReq")
	proto.RegisterType((*UpdateRecommendResp)(nil), "digger.UpdateRecommendResp")
	proto.RegisterType((*GetRecommendReq)(nil), "digger.GetRecommendReq")
	proto.RegisterType((*RecommendItem)(nil), "digger.RecommendItem")
	proto.RegisterType((*RecommendData)(nil), "digger.RecommendData")
	proto.RegisterType((*GetRecommendResp)(nil), "digger.GetRecommendResp")
	proto.RegisterType((*UserLogoutReq)(nil), "digger.UserLogoutReq")
	proto.RegisterType((*UserLogoutResp)(nil), "digger.UserLogoutResp")
	proto.RegisterType((*UserInfoData)(nil), "digger.UserInfoData")
	proto.RegisterType((*UserInfoReq)(nil), "digger.UserInfoReq")
	proto.RegisterType((*UserInfoResp)(nil), "digger.UserInfoResp")
	proto.RegisterType((*UserLoginReq)(nil), "digger.UserLoginReq")
	proto.RegisterType((*LoginData)(nil), "digger.LoginData")
	proto.RegisterType((*UserLoginResp)(nil), "digger.UserLoginResp")
}

func init() { proto.RegisterFile("digger/zwadmin.proto", fileDescriptor_2a29ab15f05ba3dc) }

var fileDescriptor_2a29ab15f05ba3dc = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x8a, 0xdc, 0x36,
	0x10, 0xc7, 0xfb, 0xdf, 0xb3, 0xbb, 0xb9, 0x3b, 0xdd, 0xe5, 0xea, 0xba, 0xa1, 0x5c, 0x4d, 0x0a,
	0x97, 0x16, 0x2e, 0x90, 0x52, 0x28, 0xe4, 0x4b, 0x13, 0x96, 0x86, 0x3b, 0xb6, 0xe5, 0xea, 0x10,
	0x0a, 0xf9, 0xa6, 0xac, 0xb5, 0x8b, 0xdb, 0xb5, 0xe5, 0x5a, 0x72, 0x72, 0xe9, 0x4b, 0xf4, 0x53,
	0xa1, 0x0f, 0xd0, 0xd7, 0xe8, 0xbb, 0x95, 0x91, 0x6c, 0xd9, 0xb2, 0x77, 0x53, 0x36, 0xdf, 0x3c,
	0x3f, 0x59, 0x33, 0x3f, 0xcd, 0x6f, 0x66, 0x24, 0x38, 0x8b, 0xe2, 0xcd, 0x86, 0xe5, 0x8f, 0xff,
	0x78, 0x47, 0xa3, 0x24, 0x4e, 0xaf, 0xb2, 0x9c, 0x4b, 0x4e, 0x46, 0x1a, 0x0d, 0xee, 0x80, 0xbc,
	0x60, 0x72, 0xc9, 0xd3, 0xcd, 0x32, 0x4e, 0xd9, 0x32, 0x16, 0x32, 0x64, 0xbf, 0x13, 0x1f, 0x26,
	0x82, 0xad, 0x8a, 0x15, 0x8f, 0x98, 0xd7, 0xbb, 0x70, 0x2e, 0xdd, 0xd0, 0xd8, 0xc4, 0x83, 0xf1,
	0x26, 0x0a, 0xa9, 0x8c, 0xb9, 0xd7, 0xbf, 0x70, 0x2e, 0x87, 0x61, 0x65, 0x92, 0x33, 0x18, 0x6e,
	0xe3, 0x24, 0x96, 0x1e, 0x28, 0x5c, 0x1b, 0xe4, 0x1c, 0x46, 0x7c, 0xbd, 0x16, 0x4c, 0x7a, 0x53,
	0x05, 0x97, 0x56, 0xf0, 0x77, 0x0f, 0x66, 0x55, 0xdc, 0x6b, 0xc9, 0x92, 0x0f, 0x06, 0x25, 0x30,
	0x48, 0x69, 0xc2, 0x54, 0x44, 0x37, 0x54, 0xdf, 0x18, 0x2e, 0xcb, 0xe3, 0x15, 0xf3, 0x06, 0x0a,
	0xd4, 0x06, 0xa2, 0x6b, 0xbe, 0x2a, 0x84, 0x37, 0xd4, 0xa8, 0x32, 0x70, 0x7f, 0x44, 0x25, 0xf3,
	0x46, 0x7a, 0x3f, 0x7e, 0x63, 0xbc, 0x1c, 0x79, 0xbf, 0x94, 0xb9, 0x37, 0xd6, 0xf1, 0x2a, 0xbb,
	0x79, 0xc8, 0x89, 0x7d, 0xc8, 0xcf, 0x01, 0x56, 0x39, 0xa3, 0x92, 0x2d, 0xd0, 0x9f, 0xab, 0xf6,
	0x35, 0x10, 0x12, 0xc0, 0x2c, 0xcb, 0x99, 0x60, 0xa9, 0xbc, 0x55, 0xe4, 0x30, 0x17, 0x4e, 0x68,
	0x61, 0xe8, 0xe3, 0x2d, 0xdd, 0x16, 0xec, 0x3a, 0x8d, 0xd8, 0x5d, 0x99, 0x96, 0x06, 0x12, 0xdc,
	0xd6, 0x99, 0x59, 0x50, 0x49, 0xf1, 0x4c, 0x92, 0x4b, 0xba, 0xf5, 0x1c, 0x9d, 0x58, 0x65, 0x90,
	0xaf, 0x60, 0x18, 0x4b, 0x96, 0x08, 0xaf, 0x77, 0xd1, 0xbf, 0x9c, 0x3e, 0x39, 0xbb, 0xd2, 0x92,
	0x5e, 0x35, 0x93, 0x1a, 0xea, 0x5f, 0x82, 0x97, 0x70, 0xda, 0x91, 0x59, 0x64, 0x98, 0x16, 0x95,
	0x6e, 0xed, 0x57, 0x7d, 0x93, 0x4b, 0x95, 0x2a, 0xaa, 0x24, 0xd8, 0xe1, 0x15, 0x09, 0xa9, 0x04,
	0xd2, 0xe0, 0x7b, 0x38, 0xbe, 0xcd, 0x79, 0x92, 0xc9, 0xe7, 0xc5, 0xfb, 0xaa, 0x72, 0x0e, 0xab,
	0x81, 0x7f, 0x1d, 0x98, 0x1b, 0x17, 0x1f, 0x55, 0x04, 0x3e, 0x4c, 0x92, 0x38, 0xbd, 0x35, 0x75,
	0xe0, 0x84, 0xc6, 0xee, 0x48, 0x31, 0xdc, 0x21, 0xc5, 0x03, 0x70, 0x55, 0xdd, 0x2c, 0xe2, 0xf5,
	0x5a, 0x55, 0x87, 0x13, 0xd6, 0x40, 0x4b, 0xec, 0x71, 0x5b, 0xec, 0x20, 0x6c, 0xd0, 0xff, 0x80,
	0x52, 0x5f, 0xdb, 0x4a, 0xdd, 0xaf, 0x72, 0x6a, 0x1d, 0xbd, 0x92, 0x2a, 0x84, 0x93, 0x56, 0x56,
	0xf7, 0x08, 0xf5, 0xc8, 0x12, 0xaa, 0xeb, 0xb4, 0xa1, 0xd4, 0x12, 0xc8, 0xab, 0x0c, 0x8b, 0xde,
	0x2c, 0xfe, 0x5f, 0x97, 0xfb, 0x30, 0x89, 0x62, 0x41, 0xdf, 0x6c, 0x59, 0xa4, 0xf2, 0x3d, 0x09,
	0x8d, 0x1d, 0x3c, 0x82, 0xd3, 0x8e, 0xb7, 0xdd, 0x1c, 0x83, 0x5f, 0xab, 0xc0, 0x21, 0x5b, 0xf1,
	0x24, 0x61, 0x69, 0x84, 0x81, 0x2b, 0x21, 0x1d, 0x5b, 0xc8, 0xbd, 0x64, 0x1e, 0xc2, 0x5c, 0x6b,
	0xc2, 0x30, 0xf7, 0x82, 0x95, 0x83, 0xc7, 0x06, 0x6b, 0x5a, 0x8d, 0x58, 0x7b, 0x68, 0xfd, 0xe9,
	0xc0, 0xd1, 0x0b, 0x26, 0x2d, 0x52, 0x58, 0x09, 0x26, 0x80, 0xfe, 0xb9, 0x06, 0x50, 0x58, 0x21,
	0xb1, 0x08, 0x7a, 0x5a, 0x58, 0x65, 0x58, 0xa4, 0xfb, 0x2d, 0xd2, 0x87, 0x75, 0xc2, 0x5f, 0x7d,
	0x98, 0x1b, 0x3a, 0xaa, 0x13, 0xee, 0x41, 0x2f, 0x8e, 0x4a, 0x22, 0xbd, 0x38, 0x3a, 0xb8, 0x33,
	0x3c, 0x18, 0xe7, 0x3f, 0xea, 0x09, 0x33, 0xd0, 0x23, 0xac, 0x34, 0xed, 0x93, 0x0e, 0xdb, 0x27,
	0xc5, 0x8e, 0xa2, 0x77, 0xba, 0x63, 0x46, 0x65, 0x47, 0x95, 0x36, 0xfa, 0xc4, 0xef, 0x05, 0x7d,
	0xaf, 0x4e, 0xe5, 0x86, 0x95, 0xa9, 0xa3, 0xe9, 0x4d, 0x53, 0xbd, 0x52, 0x9a, 0xd8, 0x43, 0x9b,
	0x85, 0x09, 0x37, 0xd3, 0xc3, 0xae, 0x46, 0xea, 0xcc, 0xce, 0xf5, 0xc0, 0xd6, 0x99, 0x7d, 0x00,
	0x6e, 0xa1, 0xc4, 0xfc, 0xa9, 0x48, 0xbc, 0x7b, 0x9a, 0xa3, 0x01, 0xb0, 0x20, 0x72, 0xb6, 0x66,
	0xb9, 0x71, 0x7b, 0xa4, 0x0b, 0xc2, 0x02, 0x31, 0xb2, 0xde, 0xa2, 0xba, 0xf7, 0x58, 0x77, 0x6f,
	0x8d, 0x74, 0xe6, 0xc3, 0x49, 0x77, 0x3e, 0x60, 0x87, 0x1b, 0x59, 0x3e, 0xa2, 0xc3, 0x2d, 0x49,
	0xab, 0x0e, 0xff, 0x19, 0x8e, 0xed, 0xe2, 0x3b, 0xac, 0xc1, 0x2d, 0x3e, 0x65, 0x83, 0x1f, 0xc1,
	0xfc, 0x95, 0x60, 0xf9, 0x92, 0x6f, 0x78, 0x81, 0x73, 0x38, 0x78, 0x08, 0xf7, 0x9a, 0xc0, 0x9e,
	0x3e, 0x90, 0x30, 0xc3, 0xbf, 0xae, 0xd3, 0x35, 0x57, 0x87, 0x3b, 0x87, 0x11, 0x7d, 0x4b, 0x25,
	0xcd, 0xcb, 0xd6, 0x2c, 0x2d, 0xcc, 0x54, 0x9c, 0xca, 0x9c, 0x47, 0xc5, 0x4a, 0xc6, 0x3c, 0x2d,
	0xeb, 0xcf, 0xc2, 0xf6, 0x5d, 0xd1, 0x39, 0xdf, 0x32, 0xe1, 0x0d, 0x2e, 0xfa, 0xa8, 0xad, 0x32,
	0x82, 0x39, 0x4c, 0xab, 0xa8, 0x48, 0x75, 0x59, 0x93, 0x38, 0xf4, 0x52, 0x6a, 0x92, 0x2f, 0x33,
	0xf1, 0x83, 0xf6, 0xb6, 0xe4, 0x9b, 0x38, 0x2d, 0x87, 0x5c, 0x21, 0x58, 0xde, 0x98, 0x37, 0xc6,
	0xc6, 0xb5, 0x8c, 0x0a, 0xf1, 0x8e, 0xe7, 0x51, 0xd5, 0x52, 0x95, 0x1d, 0x7c, 0x01, 0xae, 0xf2,
	0x51, 0x8b, 0xfe, 0x1b, 0x4b, 0x4b, 0x0f, 0xda, 0x08, 0x6e, 0x4c, 0xd2, 0x31, 0xd4, 0x1e, 0xe6,
	0x5f, 0x5a, 0xcc, 0x4f, 0xea, 0xeb, 0xb4, 0xf4, 0xad, 0x69, 0x3f, 0xf9, 0x67, 0x00, 0xe3, 0xd7,
	0xbf, 0x3c, 0xc3, 0x17, 0x1a, 0xf9, 0x0e, 0x5c, 0xe3, 0x97, 0x58, 0x67, 0xad, 0x4e, 0xe5, 0xdf,
	0xdf, 0x81, 0x8a, 0x8c, 0x7c, 0x0b, 0x93, 0x2a, 0x25, 0xe4, 0xb4, 0x9d, 0x24, 0xdc, 0x77, 0xd6,
	0x05, 0x45, 0x46, 0x9e, 0x02, 0xd4, 0xc5, 0x42, 0xda, 0xbe, 0x75, 0x45, 0xf9, 0xe7, 0xbb, 0x60,
	0x91, 0x91, 0x67, 0x30, 0x6b, 0x56, 0x33, 0xf9, 0xa4, 0xfa, 0xaf, 0x35, 0x60, 0x7d, 0x6f, 0xf7,
	0x82, 0xc8, 0xc8, 0x0d, 0x1c, 0xb5, 0x26, 0x37, 0xf1, 0x4d, 0xb4, 0xce, 0xf5, 0xe1, 0x7f, 0xb6,
	0x77, 0x4d, 0x64, 0x64, 0xd1, 0xb8, 0x92, 0xf1, 0xfa, 0x24, 0x5e, 0xe7, 0x62, 0x2c, 0xdf, 0x2a,
	0xfe, 0xa7, 0x7b, 0x56, 0x9a, 0x8c, 0xcc, 0x52, 0x9b, 0x51, 0xf3, 0x26, 0x6d, 0x33, 0xb2, 0xef,
	0xc5, 0x1b, 0x75, 0xd7, 0x34, 0xdf, 0x5e, 0xb5, 0xaf, 0xee, 0xdb, 0xbb, 0xf6, 0xb5, 0xe3, 0xc1,
	0xf6, 0x7c, 0xfa, 0xda, 0xbd, 0x7a, 0xfc, 0x54, 0xff, 0xf0, 0x66, 0xa4, 0x9e, 0xf2, 0xdf, 0xfc,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x44, 0x99, 0x6e, 0xe2, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn
var _ http.Client
var _ ezcommon.Empty

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion6

const ServiceZWAdmin = "digger.ZWAdmin"

var ServiceMethodZWAdmin = []string{
	"UserLogin",
	"UserInfo",
	"UserLogout",
	"GetRecommend",
	"UpdateRecommend",
	"PromptBuyList",
	"UpdatePromptBuy",
	"GetLongLineList",
}

// Client API for ZWAdmin service

// ZWAdminClient is the client API for ZWAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZWAdminClient interface {
	UserLogin(ctx context.T, in *UserLoginReq, opts ...grpc1.CallOption) (*UserLoginResp, error)
	UserInfo(ctx context.T, in *UserInfoReq, opts ...grpc1.CallOption) (*UserInfoResp, error)
	UserLogout(ctx context.T, in *UserLogoutReq, opts ...grpc1.CallOption) (*UserLogoutResp, error)
	GetRecommend(ctx context.T, in *GetRecommendReq, opts ...grpc1.CallOption) (*GetRecommendResp, error)
	UpdateRecommend(ctx context.T, in *UpdateRecommendReq, opts ...grpc1.CallOption) (*UpdateRecommendResp, error)
	PromptBuyList(ctx context.T, in *PromptBuyListReq, opts ...grpc1.CallOption) (*PromptBuyListResp, error)
	UpdatePromptBuy(ctx context.T, in *UpdatePromptBuyReq, opts ...grpc1.CallOption) (*UpdatePromptBuyResp, error)
	GetLongLineList(ctx context.T, in *GetLongLineListReq, opts ...grpc1.CallOption) (*GetLongLineListResp, error)
}

type zWAdminClient struct {
	cc *grpc1.ClientConn
}

var zWAdminClientOnce sync.Once
var zWAdminClientInstance ZWAdminClient

func GetZWAdmin() ZWAdminClient {
	zWAdminClientOnce.Do(func() {
		var err error
		zWAdminClientInstance, err = NewZWAdmin()
		if err != nil {
			panic(err)
		}
	})
	return zWAdminClientInstance
}

func NewZWAdmin() (ZWAdminClient, error) {
	cfg := mservice.DefaultClientConfig()
	cfg.Desc = OptionZWAdmin
	cli, err := mservice.NewClientEx(ServiceZWAdmin, cfg)
	if err != nil {
		return nil, err
	}
	return NewZWAdminClient(cli.GRPC), nil
}

func NewZWAdminClient(cc *grpc1.ClientConn) ZWAdminClient {
	return &zWAdminClient{cc}
}

func (c *zWAdminClient) UserLogin(ctx context.T, in *UserLoginReq, opts ...grpc1.CallOption) (*UserLoginResp, error) {
	out := new(UserLoginResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UserInfo(ctx context.T, in *UserInfoReq, opts ...grpc1.CallOption) (*UserInfoResp, error) {
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UserLogout(ctx context.T, in *UserLogoutReq, opts ...grpc1.CallOption) (*UserLogoutResp, error) {
	out := new(UserLogoutResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) GetRecommend(ctx context.T, in *GetRecommendReq, opts ...grpc1.CallOption) (*GetRecommendResp, error) {
	out := new(GetRecommendResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/GetRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UpdateRecommend(ctx context.T, in *UpdateRecommendReq, opts ...grpc1.CallOption) (*UpdateRecommendResp, error) {
	out := new(UpdateRecommendResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UpdateRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) PromptBuyList(ctx context.T, in *PromptBuyListReq, opts ...grpc1.CallOption) (*PromptBuyListResp, error) {
	out := new(PromptBuyListResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/PromptBuyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UpdatePromptBuy(ctx context.T, in *UpdatePromptBuyReq, opts ...grpc1.CallOption) (*UpdatePromptBuyResp, error) {
	out := new(UpdatePromptBuyResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UpdatePromptBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) GetLongLineList(ctx context.T, in *GetLongLineListReq, opts ...grpc1.CallOption) (*GetLongLineListResp, error) {
	out := new(GetLongLineListResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/GetLongLineList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZWAdminServer is the server API for ZWAdmin service.
type ZWAdminServer interface {
	UserLogin(context.T, *UserLoginReq) (*UserLoginResp, error)
	UserInfo(context.T, *UserInfoReq) (*UserInfoResp, error)
	UserLogout(context.T, *UserLogoutReq) (*UserLogoutResp, error)
	GetRecommend(context.T, *GetRecommendReq) (*GetRecommendResp, error)
	UpdateRecommend(context.T, *UpdateRecommendReq) (*UpdateRecommendResp, error)
	PromptBuyList(context.T, *PromptBuyListReq) (*PromptBuyListResp, error)
	UpdatePromptBuy(context.T, *UpdatePromptBuyReq) (*UpdatePromptBuyResp, error)
	GetLongLineList(context.T, *GetLongLineListReq) (*GetLongLineListResp, error)
}

func RegisterZWAdminGrpc(s ZWAdminGrpcRegister) {
	s.RegisterService(ServiceZWAdmin, ServiceMethodZWAdmin)
	RegisterZWAdminServer(s.GetServer(), s)
}

func RegisterZWAdminGrpcImpl(s mservice.GrpcRegister, impl ZWAdminServer) {
	s.RegisterService(ServiceZWAdmin, ServiceMethodZWAdmin)
	RegisterZWAdminServer(s.GetServer(), impl)
}

// UnimplementedZWAdminServer can be embedded to have forward compatible implementations.
type UnimplementedZWAdminServer struct {
}

func (*UnimplementedZWAdminServer) UserLogin(ctx context1.Context, req *UserLoginReq) (*UserLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedZWAdminServer) UserInfo(ctx context1.Context, req *UserInfoReq) (*UserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedZWAdminServer) UserLogout(ctx context1.Context, req *UserLogoutReq) (*UserLogoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogout not implemented")
}
func (*UnimplementedZWAdminServer) GetRecommend(ctx context1.Context, req *GetRecommendReq) (*GetRecommendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommend not implemented")
}
func (*UnimplementedZWAdminServer) UpdateRecommend(ctx context1.Context, req *UpdateRecommendReq) (*UpdateRecommendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecommend not implemented")
}
func (*UnimplementedZWAdminServer) PromptBuyList(ctx context1.Context, req *PromptBuyListReq) (*PromptBuyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromptBuyList not implemented")
}
func (*UnimplementedZWAdminServer) UpdatePromptBuy(ctx context1.Context, req *UpdatePromptBuyReq) (*UpdatePromptBuyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromptBuy not implemented")
}
func (*UnimplementedZWAdminServer) GetLongLineList(ctx context1.Context, req *GetLongLineListReq) (*GetLongLineListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongLineList not implemented")
}

func RegisterZWAdminServer(s *grpc1.Server, srv ZWAdminServer) {
	s.RegisterService(&_ZWAdmin_serviceDesc, srv)
}

type ZWAdminMServicer interface {
	RegisterServiceDesc(*ezcommon.ServiceOpDesc)
	ZWAdminServer
	mservice.WebApiRegister
	mservice.GrpcRegister
	mservice.WebSocketRegister
}

type ZWAdminGrpcRegister interface {
	ZWAdminServer
	mservice.GrpcRegister
}

func RegisterZWAdmin(s ZWAdminMServicer) {
	s.RegisterServiceDesc(OptionZWAdmin)
	RegisterZWAdminGrpc(s)
	RegisterZWAdminWebapiEx(s)
	RegisterZWAdminWebSocket(s)
}

type ZWAdminWebApiRegister interface {
	ZWAdminServer
	mservice.WebApiRegister
}

func RegisterZWAdminWebApi(s ZWAdminWebApiRegister) {
	RegisterZWAdminWebApiImpl(s, s)
}

func RegisterZWAdminWebApiImpl(s mservice.WebApiRegister, impl ZWAdminServer) {
	wrap := &ZWAdminWebapi{server: impl, register: s}
	_ = wrap
	s.WebApiRegister("/api/digger.ZWAdmin/UserLogin", wrap.UserLogin)
	s.WebApiRegister("/api/digger.ZWAdmin/UserInfo", wrap.UserInfo)
	s.WebApiRegister("/api/digger.ZWAdmin/UserLogout", wrap.UserLogout)
	s.WebApiRegister("/api/digger.ZWAdmin/GetRecommend", wrap.GetRecommend)
	s.WebApiRegister("/api/digger.ZWAdmin/UpdateRecommend", wrap.UpdateRecommend)
	s.WebApiRegister("/api/digger.ZWAdmin/PromptBuyList", wrap.PromptBuyList)
	s.WebApiRegister("/api/digger.ZWAdmin/UpdatePromptBuy", wrap.UpdatePromptBuy)
	s.WebApiRegister("/api/digger.ZWAdmin/GetLongLineList", wrap.GetLongLineList)
}

func RegisterZWAdminWebapiEx(s ZWAdminWebApiRegister) {
	wrap := &ZWAdminWebapi{server: s, register: s}
	_ = wrap
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserLogin", wrap.UserLogin)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserInfo", wrap.UserInfo)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserLogout", wrap.UserLogout)
	s.WebApiRegisterMethod("digger.ZWAdmin", "GetRecommend", wrap.GetRecommend)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UpdateRecommend", wrap.UpdateRecommend)
	s.WebApiRegisterMethod("digger.ZWAdmin", "PromptBuyList", wrap.PromptBuyList)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UpdatePromptBuy", wrap.UpdatePromptBuy)
	s.WebApiRegisterMethod("digger.ZWAdmin", "GetLongLineList", wrap.GetLongLineList)
}

type ZWAdminWebapi struct {
	server   ZWAdminServer
	register mservice.WebApiRegister
}

func (s *ZWAdminWebapi) UserLogin(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserLoginReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserLogin(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UserInfo(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserInfoReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserInfo(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UserLogout(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserLogoutReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserLogout(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) GetRecommend(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GetRecommendReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GetRecommend(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UpdateRecommend(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UpdateRecommendReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UpdateRecommend(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) PromptBuyList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(PromptBuyListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.PromptBuyList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UpdatePromptBuy(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UpdatePromptBuyReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UpdatePromptBuy(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) GetLongLineList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GetLongLineListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GetLongLineList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

type ZWAdminWebSocketApi interface {
}

type ZWAdminWebSocketRegister interface {
	ZWAdminWebSocketApi
	mservice.WebSocketRegister
}

func RegisterZWAdminWebSocket(s ZWAdminWebSocketRegister) {
}

type ZWAdminWebSocket struct {
	api      ZWAdminWebSocketApi
	register mservice.WebSocketRegister
}

func _ZWAdmin_UserLogin_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserLogin(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserLogin",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserLogin(context.From(ctx), req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UserInfo_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserInfo(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserInfo",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserInfo(context.From(ctx), req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UserLogout_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserLogout(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserLogout",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserLogout(context.From(ctx), req.(*UserLogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_GetRecommend_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).GetRecommend(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/GetRecommend",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).GetRecommend(context.From(ctx), req.(*GetRecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UpdateRecommend_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UpdateRecommend(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UpdateRecommend",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UpdateRecommend(context.From(ctx), req.(*UpdateRecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_PromptBuyList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptBuyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).PromptBuyList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/PromptBuyList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).PromptBuyList(context.From(ctx), req.(*PromptBuyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UpdatePromptBuy_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromptBuyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UpdatePromptBuy(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UpdatePromptBuy",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UpdatePromptBuy(context.From(ctx), req.(*UpdatePromptBuyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_GetLongLineList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLongLineListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).GetLongLineList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/GetLongLineList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).GetLongLineList(context.From(ctx), req.(*GetLongLineListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZWAdmin_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "digger.ZWAdmin",
	HandlerType: (*ZWAdminServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _ZWAdmin_UserLogin_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _ZWAdmin_UserInfo_Handler,
		},
		{
			MethodName: "UserLogout",
			Handler:    _ZWAdmin_UserLogout_Handler,
		},
		{
			MethodName: "GetRecommend",
			Handler:    _ZWAdmin_GetRecommend_Handler,
		},
		{
			MethodName: "UpdateRecommend",
			Handler:    _ZWAdmin_UpdateRecommend_Handler,
		},
		{
			MethodName: "PromptBuyList",
			Handler:    _ZWAdmin_PromptBuyList_Handler,
		},
		{
			MethodName: "UpdatePromptBuy",
			Handler:    _ZWAdmin_UpdatePromptBuy_Handler,
		},
		{
			MethodName: "GetLongLineList",
			Handler:    _ZWAdmin_GetLongLineList_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "digger/zwadmin.proto",
}

var OptionZWAdmin = ezcommon.GenOption([]byte{
	// 145 bytes of Option
	0x0a, 0x0e, 0x64, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x5a, 0x57, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x1a, 0x0b, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x0a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x1a, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x1a, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x1a, 0x0f, 0x0a, 0x0d, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x42, 0x75, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x11, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x42, 0x75, 0x79, 0x1a, 0x11,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x4c, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73,
	0x74,
})
