// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digger/zwadmin.proto

package digger

import (
	context1 "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc1 "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	strings "strings"
)

import (
	mservice "git.ezbuy.me/ezbuy/base/dist/mservice"
	ezcommon "git.ezbuy.me/ezbuy/base/dist/proto/common"
	context "git.ezbuy.me/ezbuy/base/misc/context"
	"net/http"
	"sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GPRecommendListReq struct {
}

func (m *GPRecommendListReq) Validate() error {
	return nil
}

func (m *GPRecommendListReq) Reset()         { *m = GPRecommendListReq{} }
func (m *GPRecommendListReq) String() string { return proto.CompactTextString(m) }
func (*GPRecommendListReq) ProtoMessage()    {}
func (*GPRecommendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{0}
}

func (m *GPRecommendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommendListReq.Unmarshal(m, b)
}
func (m *GPRecommendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommendListReq.Marshal(b, m, deterministic)
}
func (m *GPRecommendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommendListReq.Merge(m, src)
}
func (m *GPRecommendListReq) XXX_Size() int {
	return xxx_messageInfo_GPRecommendListReq.Size(m)
}
func (m *GPRecommendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommendListReq proto.InternalMessageInfo

type GPRecommend struct {
	//
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	RMIndex int32 `protobuf:"varint,4,opt,name=rMIndex,proto3" json:"rMIndex"`
	//
	PDecrease int32 `protobuf:"varint,5,opt,name=pDecrease,proto3" json:"pDecrease"`
	//
	MaxPrice float64 `protobuf:"fixed64,6,opt,name=maxPrice,proto3" json:"maxPrice"`
	//
	MaxPDay string `protobuf:"bytes,10,opt,name=maxPDay,proto3" json:"maxPDay"`
	//
	RMPrice string `protobuf:"bytes,11,opt,name=rMPrice,proto3" json:"rMPrice"`
	//
	GDDecrease int32 `protobuf:"varint,12,opt,name=gDDecrease,proto3" json:"gDDecrease"`
	//
	State string `protobuf:"bytes,13,opt,name=state,proto3" json:"state"`
	//
	UpdateDate string `protobuf:"bytes,14,opt,name=updateDate,proto3" json:"updateDate"`
	//
	PresentPrice float64 `protobuf:"fixed64,15,opt,name=presentPrice,proto3" json:"presentPrice"`
}

func (m *GPRecommend) Validate() error {
	return nil
}

func (m *GPRecommend) Reset()         { *m = GPRecommend{} }
func (m *GPRecommend) String() string { return proto.CompactTextString(m) }
func (*GPRecommend) ProtoMessage()    {}
func (*GPRecommend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{1}
}

func (m *GPRecommend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommend.Unmarshal(m, b)
}
func (m *GPRecommend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommend.Marshal(b, m, deterministic)
}
func (m *GPRecommend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommend.Merge(m, src)
}
func (m *GPRecommend) XXX_Size() int {
	return xxx_messageInfo_GPRecommend.Size(m)
}
func (m *GPRecommend) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommend.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommend proto.InternalMessageInfo

func (m *GPRecommend) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GPRecommend) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *GPRecommend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPRecommend) GetRMIndex() int32 {
	if m != nil {
		return m.RMIndex
	}
	return 0
}

func (m *GPRecommend) GetPDecrease() int32 {
	if m != nil {
		return m.PDecrease
	}
	return 0
}

func (m *GPRecommend) GetMaxPrice() float64 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *GPRecommend) GetMaxPDay() string {
	if m != nil {
		return m.MaxPDay
	}
	return ""
}

func (m *GPRecommend) GetRMPrice() string {
	if m != nil {
		return m.RMPrice
	}
	return ""
}

func (m *GPRecommend) GetGDDecrease() int32 {
	if m != nil {
		return m.GDDecrease
	}
	return 0
}

func (m *GPRecommend) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GPRecommend) GetUpdateDate() string {
	if m != nil {
		return m.UpdateDate
	}
	return ""
}

func (m *GPRecommend) GetPresentPrice() float64 {
	if m != nil {
		return m.PresentPrice
	}
	return 0
}

type GPRecommendListResp struct {
	//
	Rows []*GPRecommend `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows"`
	//
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (m *GPRecommendListResp) Validate() error {
	return nil
}

func (m *GPRecommendListResp) Reset()         { *m = GPRecommendListResp{} }
func (m *GPRecommendListResp) String() string { return proto.CompactTextString(m) }
func (*GPRecommendListResp) ProtoMessage()    {}
func (*GPRecommendListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{2}
}

func (m *GPRecommendListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPRecommendListResp.Unmarshal(m, b)
}
func (m *GPRecommendListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPRecommendListResp.Marshal(b, m, deterministic)
}
func (m *GPRecommendListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPRecommendListResp.Merge(m, src)
}
func (m *GPRecommendListResp) XXX_Size() int {
	return xxx_messageInfo_GPRecommendListResp.Size(m)
}
func (m *GPRecommendListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GPRecommendListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GPRecommendListResp proto.InternalMessageInfo

func (m *GPRecommendListResp) GetRows() []*GPRecommend {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *GPRecommendListResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UserLogoutReq struct {
}

func (m *UserLogoutReq) Validate() error {
	return nil
}

func (m *UserLogoutReq) Reset()         { *m = UserLogoutReq{} }
func (m *UserLogoutReq) String() string { return proto.CompactTextString(m) }
func (*UserLogoutReq) ProtoMessage()    {}
func (*UserLogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{3}
}

func (m *UserLogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutReq.Unmarshal(m, b)
}
func (m *UserLogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutReq.Marshal(b, m, deterministic)
}
func (m *UserLogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutReq.Merge(m, src)
}
func (m *UserLogoutReq) XXX_Size() int {
	return xxx_messageInfo_UserLogoutReq.Size(m)
}
func (m *UserLogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutReq proto.InternalMessageInfo

type UserLogoutResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
}

func (m *UserLogoutResp) Validate() error {
	return nil
}

func (m *UserLogoutResp) Reset()         { *m = UserLogoutResp{} }
func (m *UserLogoutResp) String() string { return proto.CompactTextString(m) }
func (*UserLogoutResp) ProtoMessage()    {}
func (*UserLogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{4}
}

func (m *UserLogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogoutResp.Unmarshal(m, b)
}
func (m *UserLogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogoutResp.Marshal(b, m, deterministic)
}
func (m *UserLogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogoutResp.Merge(m, src)
}
func (m *UserLogoutResp) XXX_Size() int {
	return xxx_messageInfo_UserLogoutResp.Size(m)
}
func (m *UserLogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogoutResp proto.InternalMessageInfo

func (m *UserLogoutResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type UserInfoData struct {
	//
	Avatar string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar"`
	//
	Introduction string `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction"`
	//
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	//
	Roles []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles"`
}

func (m *UserInfoData) Validate() error {
	return nil
}

func (m *UserInfoData) Reset()         { *m = UserInfoData{} }
func (m *UserInfoData) String() string { return proto.CompactTextString(m) }
func (*UserInfoData) ProtoMessage()    {}
func (*UserInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{5}
}

func (m *UserInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoData.Unmarshal(m, b)
}
func (m *UserInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoData.Marshal(b, m, deterministic)
}
func (m *UserInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoData.Merge(m, src)
}
func (m *UserInfoData) XXX_Size() int {
	return xxx_messageInfo_UserInfoData.Size(m)
}
func (m *UserInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoData proto.InternalMessageInfo

func (m *UserInfoData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfoData) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UserInfoData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfoData) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserInfoReq struct {
}

func (m *UserInfoReq) Validate() error {
	return nil
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{6}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

type UserInfoResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *UserInfoData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *UserInfoResp) Validate() error {
	return nil
}

func (m *UserInfoResp) Reset()         { *m = UserInfoResp{} }
func (m *UserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoResp) ProtoMessage()    {}
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{7}
}

func (m *UserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResp.Unmarshal(m, b)
}
func (m *UserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResp.Marshal(b, m, deterministic)
}
func (m *UserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResp.Merge(m, src)
}
func (m *UserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoResp.Size(m)
}
func (m *UserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResp proto.InternalMessageInfo

func (m *UserInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResp) GetData() *UserInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserLoginReq struct {
	//
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username"`
	//
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
}

func (m *UserLoginReq) Validate() error {
	return nil
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{8}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginData struct {
	//
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
}

func (m *LoginData) Validate() error {
	return nil
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{9}
}

func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (m *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(m, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserLoginResp struct {
	//
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	//
	Data *LoginData `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (m *UserLoginResp) Validate() error {
	return nil
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a29ab15f05ba3dc, []int{10}
}

func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserLoginResp) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GPRecommendListReq)(nil), "digger.GPRecommendListReq")
	proto.RegisterType((*GPRecommend)(nil), "digger.GPRecommend")
	proto.RegisterType((*GPRecommendListResp)(nil), "digger.GPRecommendListResp")
	proto.RegisterType((*UserLogoutReq)(nil), "digger.UserLogoutReq")
	proto.RegisterType((*UserLogoutResp)(nil), "digger.UserLogoutResp")
	proto.RegisterType((*UserInfoData)(nil), "digger.UserInfoData")
	proto.RegisterType((*UserInfoReq)(nil), "digger.UserInfoReq")
	proto.RegisterType((*UserInfoResp)(nil), "digger.UserInfoResp")
	proto.RegisterType((*UserLoginReq)(nil), "digger.UserLoginReq")
	proto.RegisterType((*LoginData)(nil), "digger.LoginData")
	proto.RegisterType((*UserLoginResp)(nil), "digger.UserLoginResp")
}

func init() { proto.RegisterFile("digger/zwadmin.proto", fileDescriptor_2a29ab15f05ba3dc) }

var fileDescriptor_2a29ab15f05ba3dc = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0x74, 0x54, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0x45, 0x8e, 0xed, 0x44, 0x23, 0xff, 0xe1, 0x37, 0xd6, 0x2f, 0x08, 0xb7, 0x14, 0x57, 0xb4,
	0xd4, 0x27, 0x07, 0x5c, 0x0a, 0x85, 0x9c, 0x5a, 0x4c, 0x4b, 0x82, 0x0b, 0x41, 0xb4, 0x14, 0x72,
	0xdb, 0x4a, 0x5b, 0x23, 0x1a, 0x6b, 0x37, 0xbb, 0xeb, 0x3a, 0xed, 0xb5, 0x1f, 0xb0, 0x5f, 0xa9,
	0xec, 0xac, 0x25, 0xcb, 0x8e, 0x7d, 0xdb, 0xf7, 0x66, 0x76, 0xe6, 0xed, 0x9b, 0x91, 0x20, 0xcc,
	0xf2, 0xc5, 0x82, 0xab, 0x8b, 0xdf, 0x6b, 0x96, 0x2d, 0xf3, 0x62, 0x22, 0x95, 0x30, 0x02, 0xdb,
	0x8e, 0x8d, 0x43, 0xc0, 0x8f, 0x37, 0x09, 0x4f, 0xc5, 0x72, 0xc9, 0x8b, 0x6c, 0x9e, 0x6b, 0x93,
	0xf0, 0xfb, 0xf8, 0x6f, 0x03, 0x82, 0x1a, 0x8d, 0x3d, 0x68, 0xe4, 0x59, 0xe4, 0x8d, 0xbc, 0x71,
	0x2b, 0x69, 0xe4, 0x19, 0x0e, 0xe1, 0x4c, 0xf3, 0x74, 0x95, 0x8a, 0x8c, 0x47, 0x8d, 0x91, 0x37,
	0xf6, 0x93, 0x0a, 0x23, 0x42, 0xb3, 0x60, 0x4b, 0x1e, 0x9d, 0x10, 0x4f, 0x67, 0x8c, 0xe0, 0x54,
	0x7d, 0xba, 0x2a, 0x32, 0xfe, 0x10, 0x35, 0xa9, 0x48, 0x09, 0xf1, 0x29, 0xf8, 0x72, 0xc6, 0x53,
	0xc5, 0x99, 0xe6, 0x51, 0x8b, 0x62, 0x5b, 0xc2, 0xf6, 0x59, 0xb2, 0x87, 0x1b, 0x95, 0xa7, 0x3c,
	0x6a, 0x8f, 0xbc, 0xb1, 0x97, 0x54, 0xd8, 0xd6, 0xb4, 0xe7, 0x19, 0xfb, 0x15, 0x01, 0xb5, 0x2a,
	0xa1, 0xeb, 0xe6, 0x2e, 0x05, 0x2e, 0xb2, 0x81, 0xf8, 0x0c, 0x60, 0x31, 0xab, 0xda, 0x75, 0xa8,
	0x5d, 0x8d, 0xc1, 0x10, 0x5a, 0xda, 0x30, 0xc3, 0xa3, 0x2e, 0xdd, 0x73, 0xc0, 0xde, 0x5a, 0xc9,
	0x8c, 0x19, 0x3e, 0xb3, 0xa1, 0x1e, 0x85, 0x6a, 0x0c, 0xc6, 0xd0, 0x91, 0x8a, 0x6b, 0x5e, 0x18,
	0xd7, 0xb4, 0x4f, 0x4a, 0x77, 0xb8, 0xf8, 0x33, 0x0c, 0x1e, 0xf9, 0xac, 0x25, 0xbe, 0x82, 0xa6,
	0x12, 0x6b, 0x1d, 0x79, 0xa3, 0x93, 0x71, 0x30, 0x1d, 0x4c, 0xdc, 0x54, 0x26, 0xb5, 0xd4, 0x84,
	0x12, 0xac, 0x32, 0x23, 0x0c, 0xbb, 0x23, 0xbb, 0x5b, 0x89, 0x03, 0x71, 0x1f, 0xba, 0x5f, 0x34,
	0x57, 0x73, 0xb1, 0x10, 0x2b, 0x1a, 0xdc, 0x0b, 0xe8, 0xd5, 0x09, 0x2d, 0xed, 0x38, 0x68, 0x4c,
	0x6e, 0x78, 0x74, 0x8e, 0x0d, 0x74, 0x6c, 0xd6, 0x55, 0xf1, 0x5d, 0xcc, 0x98, 0x61, 0x78, 0x0e,
	0x6d, 0xf6, 0x93, 0x19, 0xa6, 0x28, 0xcb, 0x4f, 0x36, 0xc8, 0x3e, 0x2c, 0x2f, 0x8c, 0x12, 0xd9,
	0x2a, 0x35, 0xb9, 0x28, 0x36, 0xa3, 0xde, 0xe1, 0x0e, 0x8e, 0x3b, 0x84, 0x96, 0x12, 0x77, 0x5c,
	0x47, 0xcd, 0xd1, 0x89, 0xb5, 0x91, 0x40, 0xdc, 0x85, 0xa0, 0xec, 0x6a, 0xa5, 0xce, 0xb7, 0x22,
	0x8e, 0x09, 0xc5, 0x31, 0x34, 0x33, 0x66, 0x18, 0x35, 0x0e, 0xa6, 0x61, 0x69, 0x4f, 0x5d, 0x7c,
	0x42, 0x19, 0xf1, 0x07, 0x57, 0x6d, 0x2e, 0x16, 0x79, 0x91, 0xf0, 0x7b, 0xbb, 0x39, 0x2b, 0xcd,
	0x15, 0x49, 0x73, 0x8f, 0xaa, 0xb0, 0x8d, 0x49, 0xa6, 0xf5, 0x5a, 0xa8, 0xac, 0xdc, 0xde, 0x12,
	0xc7, 0xcf, 0xc1, 0xa7, 0x1a, 0xe4, 0x0b, 0x99, 0xfe, 0x83, 0x17, 0x9b, 0x0a, 0x0e, 0xc4, 0xd7,
	0x95, 0xe9, 0xb6, 0xd5, 0x11, 0xe5, 0x2f, 0x77, 0x94, 0xff, 0x57, 0x2a, 0xaf, 0x6a, 0x3b, 0xd9,
	0xd3, 0x3f, 0x0d, 0x38, 0xbd, 0xfd, 0xfa, 0xce, 0x7e, 0x98, 0xf8, 0x16, 0xfc, 0xaa, 0x2e, 0xee,
	0xbc, 0xb5, 0x7c, 0xd5, 0xf0, 0xff, 0x03, 0xac, 0x96, 0xf8, 0x06, 0xce, 0x4a, 0x4b, 0x70, 0xb0,
	0x6f, 0x92, 0xbd, 0x17, 0x3e, 0x26, 0xb5, 0xc4, 0x4b, 0x80, 0xed, 0xb2, 0xe0, 0x7e, 0x6d, 0xb7,
	0x51, 0xc3, 0xf3, 0x43, 0xb4, 0x96, 0x78, 0x0d, 0xfd, 0xbd, 0x85, 0xc6, 0xe1, 0x81, 0xf5, 0xdd,
	0xfc, 0x51, 0x86, 0x4f, 0x8e, 0xc6, 0xb4, 0x7c, 0x1f, 0xdc, 0xfa, 0x93, 0x8b, 0x4b, 0x97, 0xf0,
	0xad, 0x4d, 0x3f, 0xa8, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0x7a, 0xb0, 0xa9, 0xb8,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn
var _ http.Client
var _ ezcommon.Empty

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion6

const ServiceZWAdmin = "digger.ZWAdmin"

var ServiceMethodZWAdmin = []string{
	"UserLogin",
	"UserInfo",
	"UserLogout",
	"GPRecommendList",
}

// Client API for ZWAdmin service

// ZWAdminClient is the client API for ZWAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZWAdminClient interface {
	UserLogin(ctx context.T, in *UserLoginReq, opts ...grpc1.CallOption) (*UserLoginResp, error)
	UserInfo(ctx context.T, in *UserInfoReq, opts ...grpc1.CallOption) (*UserInfoResp, error)
	UserLogout(ctx context.T, in *UserLogoutReq, opts ...grpc1.CallOption) (*UserLogoutResp, error)
	GPRecommendList(ctx context.T, in *GPRecommendListReq, opts ...grpc1.CallOption) (*GPRecommendListResp, error)
}

type zWAdminClient struct {
	cc *grpc1.ClientConn
}

var zWAdminClientOnce sync.Once
var zWAdminClientInstance ZWAdminClient

func GetZWAdmin() ZWAdminClient {
	zWAdminClientOnce.Do(func() {
		var err error
		zWAdminClientInstance, err = NewZWAdmin()
		if err != nil {
			panic(err)
		}
	})
	return zWAdminClientInstance
}

func NewZWAdmin() (ZWAdminClient, error) {
	cfg := mservice.DefaultClientConfig()
	cfg.Desc = OptionZWAdmin
	cli, err := mservice.NewClientEx(ServiceZWAdmin, cfg)
	if err != nil {
		return nil, err
	}
	return NewZWAdminClient(cli.GRPC), nil
}

func NewZWAdminClient(cc *grpc1.ClientConn) ZWAdminClient {
	return &zWAdminClient{cc}
}

func (c *zWAdminClient) UserLogin(ctx context.T, in *UserLoginReq, opts ...grpc1.CallOption) (*UserLoginResp, error) {
	out := new(UserLoginResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UserInfo(ctx context.T, in *UserInfoReq, opts ...grpc1.CallOption) (*UserInfoResp, error) {
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) UserLogout(ctx context.T, in *UserLogoutReq, opts ...grpc1.CallOption) (*UserLogoutResp, error) {
	out := new(UserLogoutResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/UserLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zWAdminClient) GPRecommendList(ctx context.T, in *GPRecommendListReq, opts ...grpc1.CallOption) (*GPRecommendListResp, error) {
	out := new(GPRecommendListResp)
	err := c.cc.Invoke(ctx, "/digger.ZWAdmin/GPRecommendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZWAdminServer is the server API for ZWAdmin service.
type ZWAdminServer interface {
	UserLogin(context.T, *UserLoginReq) (*UserLoginResp, error)
	UserInfo(context.T, *UserInfoReq) (*UserInfoResp, error)
	UserLogout(context.T, *UserLogoutReq) (*UserLogoutResp, error)
	GPRecommendList(context.T, *GPRecommendListReq) (*GPRecommendListResp, error)
}

func RegisterZWAdminGrpc(s ZWAdminGrpcRegister) {
	s.RegisterService(ServiceZWAdmin, ServiceMethodZWAdmin)
	RegisterZWAdminServer(s.GetServer(), s)
}

func RegisterZWAdminGrpcImpl(s mservice.GrpcRegister, impl ZWAdminServer) {
	s.RegisterService(ServiceZWAdmin, ServiceMethodZWAdmin)
	RegisterZWAdminServer(s.GetServer(), impl)
}

// UnimplementedZWAdminServer can be embedded to have forward compatible implementations.
type UnimplementedZWAdminServer struct {
}

func (*UnimplementedZWAdminServer) UserLogin(ctx context1.Context, req *UserLoginReq) (*UserLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedZWAdminServer) UserInfo(ctx context1.Context, req *UserInfoReq) (*UserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedZWAdminServer) UserLogout(ctx context1.Context, req *UserLogoutReq) (*UserLogoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogout not implemented")
}
func (*UnimplementedZWAdminServer) GPRecommendList(ctx context1.Context, req *GPRecommendListReq) (*GPRecommendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GPRecommendList not implemented")
}

func RegisterZWAdminServer(s *grpc1.Server, srv ZWAdminServer) {
	s.RegisterService(&_ZWAdmin_serviceDesc, srv)
}

type ZWAdminMServicer interface {
	RegisterServiceDesc(*ezcommon.ServiceOpDesc)
	ZWAdminServer
	mservice.WebApiRegister
	mservice.GrpcRegister
	mservice.WebSocketRegister
}

type ZWAdminGrpcRegister interface {
	ZWAdminServer
	mservice.GrpcRegister
}

func RegisterZWAdmin(s ZWAdminMServicer) {
	s.RegisterServiceDesc(OptionZWAdmin)
	RegisterZWAdminGrpc(s)
	RegisterZWAdminWebapiEx(s)
	RegisterZWAdminWebSocket(s)
}

type ZWAdminWebApiRegister interface {
	ZWAdminServer
	mservice.WebApiRegister
}

func RegisterZWAdminWebApi(s ZWAdminWebApiRegister) {
	RegisterZWAdminWebApiImpl(s, s)
}

func RegisterZWAdminWebApiImpl(s mservice.WebApiRegister, impl ZWAdminServer) {
	wrap := &ZWAdminWebapi{server: impl, register: s}
	_ = wrap
	s.WebApiRegister("/api/digger.ZWAdmin/UserLogin", wrap.UserLogin)
	s.WebApiRegister("/api/digger.ZWAdmin/UserInfo", wrap.UserInfo)
	s.WebApiRegister("/api/digger.ZWAdmin/UserLogout", wrap.UserLogout)
	s.WebApiRegister("/api/digger.ZWAdmin/GPRecommendList", wrap.GPRecommendList)
}

func RegisterZWAdminWebapiEx(s ZWAdminWebApiRegister) {
	wrap := &ZWAdminWebapi{server: s, register: s}
	_ = wrap
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserLogin", wrap.UserLogin)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserInfo", wrap.UserInfo)
	s.WebApiRegisterMethod("digger.ZWAdmin", "UserLogout", wrap.UserLogout)
	s.WebApiRegisterMethod("digger.ZWAdmin", "GPRecommendList", wrap.GPRecommendList)
}

type ZWAdminWebapi struct {
	server   ZWAdminServer
	register mservice.WebApiRegister
}

func (s *ZWAdminWebapi) UserLogin(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserLoginReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserLogin(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UserInfo(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserInfoReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserInfo(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) UserLogout(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(UserLogoutReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.UserLogout(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

func (s *ZWAdminWebapi) GPRecommendList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GPRecommendListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GPRecommendList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

type ZWAdminWebSocketApi interface {
}

type ZWAdminWebSocketRegister interface {
	ZWAdminWebSocketApi
	mservice.WebSocketRegister
}

func RegisterZWAdminWebSocket(s ZWAdminWebSocketRegister) {
}

type ZWAdminWebSocket struct {
	api      ZWAdminWebSocketApi
	register mservice.WebSocketRegister
}

func _ZWAdmin_UserLogin_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserLogin(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserLogin",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserLogin(context.From(ctx), req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UserInfo_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserInfo(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserInfo",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserInfo(context.From(ctx), req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_UserLogout_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).UserLogout(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/UserLogout",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).UserLogout(context.From(ctx), req.(*UserLogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZWAdmin_GPRecommendList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPRecommendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZWAdminServer).GPRecommendList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.ZWAdmin/GPRecommendList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(ZWAdminServer).GPRecommendList(context.From(ctx), req.(*GPRecommendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZWAdmin_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "digger.ZWAdmin",
	HandlerType: (*ZWAdminServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _ZWAdmin_UserLogin_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _ZWAdmin_UserInfo_Handler,
		},
		{
			MethodName: "UserLogout",
			Handler:    _ZWAdmin_UserLogout_Handler,
		},
		{
			MethodName: "GPRecommendList",
			Handler:    _ZWAdmin_GPRecommendList_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "digger/zwadmin.proto",
}

var OptionZWAdmin = ezcommon.GenOption([]byte{
	// 74 bytes of Option
	0x0a, 0x0e, 0x64, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x5a, 0x57, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x1a, 0x0b, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x0a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x1a, 0x11, 0x0a, 0x0f, 0x47, 0x50, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
})
