// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digger/fountain.proto

package digger

import (
	context1 "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc1 "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	strings "strings"
)

import (
	mservice "git.ezbuy.me/ezbuy/base/dist/mservice"
	ezcommon "git.ezbuy.me/ezbuy/base/dist/proto/common"
	context "git.ezbuy.me/ezbuy/base/misc/context"
	"net/http"
	"sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = strings.TrimPrefix

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRecommendListReq struct {
	//
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset"`
	//
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
}

func (m *GetRecommendListReq) Validate() error {
	return nil
}

func (m *GetRecommendListReq) Reset()         { *m = GetRecommendListReq{} }
func (m *GetRecommendListReq) String() string { return proto.CompactTextString(m) }
func (*GetRecommendListReq) ProtoMessage()    {}
func (*GetRecommendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{0}
}

func (m *GetRecommendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendListReq.Unmarshal(m, b)
}
func (m *GetRecommendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendListReq.Marshal(b, m, deterministic)
}
func (m *GetRecommendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendListReq.Merge(m, src)
}
func (m *GetRecommendListReq) XXX_Size() int {
	return xxx_messageInfo_GetRecommendListReq.Size(m)
}
func (m *GetRecommendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendListReq proto.InternalMessageInfo

func (m *GetRecommendListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRecommendListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RecommendData struct {
	//
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	//
	Secucode string `protobuf:"bytes,2,opt,name=secucode,proto3" json:"secucode"`
	//
	ValueIndex float32 `protobuf:"fixed32,3,opt,name=valueIndex,proto3" json:"valueIndex"`
	//
	CumulantPrice string `protobuf:"bytes,4,opt,name=cumulantPrice,proto3" json:"cumulantPrice"`
	//
	CumulantFocus string `protobuf:"bytes,5,opt,name=cumulantFocus,proto3" json:"cumulantFocus"`
	//
	CumulantDate string `protobuf:"bytes,6,opt,name=cumulantDate,proto3" json:"cumulantDate"`
	//
	EndDate string `protobuf:"bytes,7,opt,name=endDate,proto3" json:"endDate"`
	//
	CreateDate int64 `protobuf:"varint,8,opt,name=createDate,proto3" json:"createDate"`
}

func (m *RecommendData) Validate() error {
	return nil
}

func (m *RecommendData) Reset()         { *m = RecommendData{} }
func (m *RecommendData) String() string { return proto.CompactTextString(m) }
func (*RecommendData) ProtoMessage()    {}
func (*RecommendData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{1}
}

func (m *RecommendData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendData.Unmarshal(m, b)
}
func (m *RecommendData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendData.Marshal(b, m, deterministic)
}
func (m *RecommendData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendData.Merge(m, src)
}
func (m *RecommendData) XXX_Size() int {
	return xxx_messageInfo_RecommendData.Size(m)
}
func (m *RecommendData) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendData.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendData proto.InternalMessageInfo

func (m *RecommendData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RecommendData) GetSecucode() string {
	if m != nil {
		return m.Secucode
	}
	return ""
}

func (m *RecommendData) GetValueIndex() float32 {
	if m != nil {
		return m.ValueIndex
	}
	return 0
}

func (m *RecommendData) GetCumulantPrice() string {
	if m != nil {
		return m.CumulantPrice
	}
	return ""
}

func (m *RecommendData) GetCumulantFocus() string {
	if m != nil {
		return m.CumulantFocus
	}
	return ""
}

func (m *RecommendData) GetCumulantDate() string {
	if m != nil {
		return m.CumulantDate
	}
	return ""
}

func (m *RecommendData) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *RecommendData) GetCreateDate() int64 {
	if m != nil {
		return m.CreateDate
	}
	return 0
}

type GetRecommendListResp struct {
	//
	Rows []*RecommendData `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows"`
	//
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (m *GetRecommendListResp) Validate() error {
	return nil
}

func (m *GetRecommendListResp) Reset()         { *m = GetRecommendListResp{} }
func (m *GetRecommendListResp) String() string { return proto.CompactTextString(m) }
func (*GetRecommendListResp) ProtoMessage()    {}
func (*GetRecommendListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d02a9263fc9247, []int{2}
}

func (m *GetRecommendListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecommendListResp.Unmarshal(m, b)
}
func (m *GetRecommendListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecommendListResp.Marshal(b, m, deterministic)
}
func (m *GetRecommendListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecommendListResp.Merge(m, src)
}
func (m *GetRecommendListResp) XXX_Size() int {
	return xxx_messageInfo_GetRecommendListResp.Size(m)
}
func (m *GetRecommendListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecommendListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecommendListResp proto.InternalMessageInfo

func (m *GetRecommendListResp) GetRows() []*RecommendData {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *GetRecommendListResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRecommendListReq)(nil), "digger.GetRecommendListReq")
	proto.RegisterType((*RecommendData)(nil), "digger.RecommendData")
	proto.RegisterType((*GetRecommendListResp)(nil), "digger.GetRecommendListResp")
}

func init() { proto.RegisterFile("digger/fountain.proto", fileDescriptor_a9d02a9263fc9247) }

var fileDescriptor_a9d02a9263fc9247 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x04, 0x03, 0x02, 0x01, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x69, 0xb7, 0x75, 0xdb, 0xd9, 0xbb, 0x17, 0x89, 0x9b, 0x84, 0x29, 0x52, 0x8a, 0x17,
	0xf5, 0xa6, 0x83, 0x79, 0xe9, 0x9d, 0x8e, 0x89, 0xa0, 0x20, 0xb9, 0x11, 0xbd, 0x8b, 0xe9, 0xd9,
	0x08, 0xb4, 0xcd, 0x6c, 0x12, 0xf5, 0x0b, 0xf8, 0xbd, 0x65, 0xe9, 0x3a, 0x56, 0xff, 0x5c, 0x3e,
	0xbf, 0xf3, 0x9c, 0x93, 0xe4, 0x39, 0x81, 0x71, 0x2a, 0x57, 0x2b, 0x2c, 0xa7, 0x4b, 0x65, 0x0b,
	0xc3, 0x65, 0x91, 0xac, 0x4b, 0x65, 0x14, 0x09, 0x2a, 0x1c, 0x5d, 0xc3, 0xe1, 0x0d, 0x1a, 0x86,
	0x42, 0xe5, 0x39, 0x16, 0xe9, 0x9d, 0xd4, 0x86, 0xe1, 0x2b, 0x39, 0x82, 0x40, 0x2d, 0x97, 0x1a,
	0x0d, 0xf5, 0x42, 0x2f, 0xee, 0xb0, 0xad, 0x22, 0x23, 0xe8, 0x64, 0x32, 0x97, 0x86, 0xfa, 0x0e,
	0x57, 0x22, 0xfa, 0xf4, 0x61, 0xb8, 0x1b, 0x31, 0xe7, 0x86, 0x93, 0xff, 0xe0, 0xcb, 0x74, 0xdb,
	0xeb, 0xcb, 0x94, 0x4c, 0xa0, 0xa7, 0x51, 0x58, 0xa1, 0x52, 0x74, 0xad, 0x7d, 0xb6, 0xd3, 0xe4,
	0x14, 0xe0, 0x8d, 0x67, 0x16, 0x6f, 0x8b, 0x14, 0x3f, 0x68, 0x2b, 0xf4, 0x62, 0x9f, 0xed, 0x11,
	0x72, 0x06, 0x43, 0x61, 0x73, 0x9b, 0xf1, 0xc2, 0x3c, 0x94, 0x52, 0x20, 0x6d, 0xbb, 0x01, 0x4d,
	0xb8, 0xef, 0x5a, 0x28, 0x61, 0x35, 0xed, 0x34, 0x5d, 0x0e, 0x92, 0x08, 0xfe, 0xd5, 0x60, 0xce,
	0x0d, 0xd2, 0xc0, 0x99, 0x1a, 0x8c, 0x50, 0xe8, 0x56, 0xcf, 0x40, 0xda, 0x75, 0xe5, 0x5a, 0x6e,
	0x6e, 0x2a, 0x4a, 0xe4, 0x06, 0x5d, 0xb1, 0x17, 0x7a, 0x71, 0x8b, 0xed, 0x91, 0xe8, 0x11, 0x46,
	0x3f, 0xc3, 0xd4, 0x6b, 0x72, 0x0e, 0xed, 0x52, 0xbd, 0x6b, 0xea, 0x85, 0xad, 0x78, 0x30, 0x1b,
	0x27, 0x55, 0xf6, 0x49, 0x23, 0x32, 0xe6, 0x2c, 0x9b, 0x80, 0x8d, 0x32, 0x3c, 0xab, 0x03, 0x76,
	0x62, 0xf6, 0x04, 0xbd, 0xc5, 0x76, 0x7f, 0xe4, 0x1e, 0x0e, 0xbe, 0x1f, 0x42, 0x8e, 0xeb, 0x91,
	0xbf, 0xec, 0x72, 0x72, 0xf2, 0x77, 0x51, 0xaf, 0xaf, 0x06, 0xcf, 0xfd, 0x64, 0x7a, 0x59, 0x39,
	0x5e, 0x02, 0xf7, 0x39, 0x2e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xaf, 0x5c, 0xbf, 0x35,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context1.Context
var _ grpc1.ClientConn
var _ http.Client
var _ ezcommon.Empty

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion6

const ServiceFountain = "digger.Fountain"

var ServiceMethodFountain = []string{
	"GetRecommendList",
}

// Client API for Fountain service

// FountainClient is the client API for Fountain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FountainClient interface {
	GetRecommendList(ctx context.T, in *GetRecommendListReq, opts ...grpc1.CallOption) (*GetRecommendListResp, error)
}

type fountainClient struct {
	cc *grpc1.ClientConn
}

var fountainClientOnce sync.Once
var fountainClientInstance FountainClient

func GetFountain() FountainClient {
	fountainClientOnce.Do(func() {
		var err error
		fountainClientInstance, err = NewFountain()
		if err != nil {
			panic(err)
		}
	})
	return fountainClientInstance
}

func NewFountain() (FountainClient, error) {
	cfg := mservice.DefaultClientConfig()
	cfg.Desc = OptionFountain
	cli, err := mservice.NewClientEx(ServiceFountain, cfg)
	if err != nil {
		return nil, err
	}
	return NewFountainClient(cli.GRPC), nil
}

func NewFountainClient(cc *grpc1.ClientConn) FountainClient {
	return &fountainClient{cc}
}

func (c *fountainClient) GetRecommendList(ctx context.T, in *GetRecommendListReq, opts ...grpc1.CallOption) (*GetRecommendListResp, error) {
	out := new(GetRecommendListResp)
	err := c.cc.Invoke(ctx, "/digger.Fountain/GetRecommendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FountainServer is the server API for Fountain service.
type FountainServer interface {
	GetRecommendList(context.T, *GetRecommendListReq) (*GetRecommendListResp, error)
}

func RegisterFountainGrpc(s FountainGrpcRegister) {
	s.RegisterService(ServiceFountain, ServiceMethodFountain)
	RegisterFountainServer(s.GetServer(), s)
}

func RegisterFountainGrpcImpl(s mservice.GrpcRegister, impl FountainServer) {
	s.RegisterService(ServiceFountain, ServiceMethodFountain)
	RegisterFountainServer(s.GetServer(), impl)
}

// UnimplementedFountainServer can be embedded to have forward compatible implementations.
type UnimplementedFountainServer struct {
}

func (*UnimplementedFountainServer) GetRecommendList(ctx context1.Context, req *GetRecommendListReq) (*GetRecommendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendList not implemented")
}

func RegisterFountainServer(s *grpc1.Server, srv FountainServer) {
	s.RegisterService(&_Fountain_serviceDesc, srv)
}

type FountainMServicer interface {
	RegisterServiceDesc(*ezcommon.ServiceOpDesc)
	FountainServer
	mservice.WebApiRegister
	mservice.GrpcRegister
	mservice.WebSocketRegister
}

type FountainGrpcRegister interface {
	FountainServer
	mservice.GrpcRegister
}

func RegisterFountain(s FountainMServicer) {
	s.RegisterServiceDesc(OptionFountain)
	RegisterFountainGrpc(s)
	RegisterFountainWebapiEx(s)
	RegisterFountainWebSocket(s)
}

type FountainWebApiRegister interface {
	FountainServer
	mservice.WebApiRegister
}

func RegisterFountainWebApi(s FountainWebApiRegister) {
	RegisterFountainWebApiImpl(s, s)
}

func RegisterFountainWebApiImpl(s mservice.WebApiRegister, impl FountainServer) {
	wrap := &FountainWebapi{server: impl, register: s}
	_ = wrap
	s.WebApiRegister("/api/digger.Fountain/GetRecommendList", wrap.GetRecommendList)
}

func RegisterFountainWebapiEx(s FountainWebApiRegister) {
	wrap := &FountainWebapi{server: s, register: s}
	_ = wrap
	s.WebApiRegisterMethod("digger.Fountain", "GetRecommendList", wrap.GetRecommendList)
}

type FountainWebapi struct {
	server   FountainServer
	register mservice.WebApiRegister
}

func (s *FountainWebapi) GetRecommendList(ctx *context.T, w http.ResponseWriter, req *http.Request) {
	params := new(GetRecommendListReq)
	if err := s.register.WebApiDecode(ctx, req, params); err != nil {
		s.register.WebApiHandleResp(ctx, w, nil, err)
		return
	}
	resp, err := s.server.GetRecommendList(*ctx, params)
	s.register.WebApiHandleResp(ctx, w, resp, err)
}

type FountainWebSocketApi interface {
}

type FountainWebSocketRegister interface {
	FountainWebSocketApi
	mservice.WebSocketRegister
}

func RegisterFountainWebSocket(s FountainWebSocketRegister) {
}

type FountainWebSocket struct {
	api      FountainWebSocketApi
	register mservice.WebSocketRegister
}

func _Fountain_GetRecommendList_Handler(srv interface{}, ctx context1.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if err := in.Validate(); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FountainServer).GetRecommendList(context.From(ctx), in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digger.Fountain/GetRecommendList",
	}
	handler := func(ctx context1.Context, req interface{}) (interface{}, error) {
		return srv.(FountainServer).GetRecommendList(context.From(ctx), req.(*GetRecommendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fountain_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "digger.Fountain",
	HandlerType: (*FountainServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetRecommendList",
			Handler:    _Fountain_GetRecommendList_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "digger/fountain.proto",
}

var OptionFountain = ezcommon.GenOption([]byte{
	// 37 bytes of Option
	0x0a, 0x0f, 0x64, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x1a, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74,
})
