/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */



export interface LoginReq {
	username?: string;
	password?: string;
	sourceCode?: string;
}

export interface LoginRsp {
	status?: boolean;
	code?: string;
	message?: string;
	data?: LoginSuccessData;
}

export interface LoginSuccessData {
	/**
	 * @pattern ^\d+$
	 */
	userId?: string;
	needModify?: boolean;
	token?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	timeToExpire?: number;
	menuFunctionsData?: MenuFunctionsData;
	groupsData?: GroupsData;
	rolesData?: RolesData;
	modifyMgs?: string;
	name?: string;
	displayName?: string;
	applicationUrl?: string;
}

export interface GroupInfo {
	/**
	 * @pattern ^\d+$
	 */
	groupId?: string;
	groupName?: string;
}

export interface GroupsData {
	groupInfo?: GroupInfo[];
}

export interface RoleInfo {
	/**
	 * @pattern ^\d+$
	 */
	roleId?: string;
	roleName?: string;
}

export interface RolesData {
	roleInfo?: RoleInfo[];
}

export interface Menus {
	/**
	 * @pattern ^\d+$
	 */
	menuId?: string;
	menuName?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	menuLevel?: number;
	url?: string;
	isUnfold?: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	order?: number;
	newWindow?: boolean;
	icon?: string;
	childMenus?: Menus[];
}

export interface Function {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	menuId?: number;
	functionName?: string;
	functionCode?: string;
	interfaceUrl?: string;
}

export interface MenuFunctionsData {
	menus?: Menus[];
	functions?: Function[];
}

export interface GlobalCustomerResp {
	result?: GlobalCustomerResult;
	info?: GlobalCustomerInfo;
}

export interface GlobalCustomerResult {
	result?: boolean;
	msg?: string;
}

export interface GlobalCustomerInfo {
	/**
	 * @pattern ^\d+$
	 */
	userId?: string;
	defaultShipTo?: string;
	sex?: string;
	/**
	 * @pattern ^\d+$
	 */
	birthDate?: string;
	notificationEmail?: string;
	nickName?: string;
	email?: string;
	/**
	 * @pattern ^\d+$
	 */
	registerDate?: string;
	/**
	 * @pattern ^\d+$
	 */
	lastLoginDate?: string;
	blocked?: boolean;
	registerSource?: string;
	hasPassword?: boolean;
	newUser?: boolean;
	countryCode?: string;
	languageCode?: string;
	currencyCode?: string;
	countryTranslateText?: string;
	identifyCode?: string;
}