/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import webapi from "./webapi";




export interface TBoolReply {
	code: number;
	msg: string;
	data?: boolean;
}
export interface TCheckUserReply {
	isExist: boolean;
}
export interface TGetOperLogReply {
	operDate: string;
	operDesc: string;
	operType: string;
	operedUser: string;
}
export interface TSystem {
	id: string;
	name: string;
}
export interface TSystemsReply {
	code: number;
	msg: string;
	data?: string[];
}
export interface TUser {
	username: string;
	systems?: string[];
}
export interface TUserReply {
	code: number;
	msg: string;
	data?: TUser;
}
export interface TUsersReply {
	code: number;
	msg: string;
	data?: TUser[];
}


export function AssignSystemsToUser(username: string, systems: string[]): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.AssignSystemsToUser", { username, systems });
}

export function ChangePassword(username: string, password: string, newPassword: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.ChangePassword", { username, password, newPassword });
}

export function CheckUser(): Promise<TCheckUserReply> {
	return webapi<TCheckUserReply>("Login.CheckUser", {  });
}

export function CreateSystem(system: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.CreateSystem", { system });
}

export function CreateUser(username: string, password: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.CreateUser", { username, password });
}

export function DeleteUser(username: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.DeleteUser", { username });
}

export function GetAdminOperLog(username: string, dateMonth: string): Promise<TGetOperLogReply[]> {
	return webapi<TGetOperLogReply[]>("Login.GetAdminOperLog", { username, dateMonth });
}

export function GetAdminUser(): Promise<string[]> {
	return webapi<string[]>("Login.GetAdminUser", {  });
}

export function GetSystems(): Promise<TSystemsReply> {
	return webapi<TSystemsReply>("Login.GetSystems", {  });
}

export function GetUsers(): Promise<TUsersReply> {
	return webapi<TUsersReply>("Login.GetUsers", {  });
}

export function Login(username: string, password: string): Promise<TUserReply> {
	return webapi<TUserReply>("Login.Login", { username, password });
}

export function Logout(username: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.Logout", { username });
}

export function QueryUser(keyword: string, offset: number, limit: number): Promise<TUser[]> {
	return webapi<TUser[]>("Login.QueryUser", { keyword, offset, limit });
}

export function ResetPassword(username: string): Promise<TBoolReply> {
	return webapi<TBoolReply>("Login.ResetPassword", { username });
}



export default {
	AssignSystemsToUser,
	ChangePassword,
	CheckUser,
	CreateSystem,
	CreateUser,
	DeleteUser,
	GetAdminOperLog,
	GetAdminUser,
	GetSystems,
	GetUsers,
	Login,
	Logout,
	QueryUser,
	ResetPassword,
};

