/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */



export enum DeliveryType {
	ALL = "ALL",
	Home = "Home",
	MRT = "MRT",
	WAREHOUSE = "WAREHOUSE",
	NeighbourhoodStation = "NeighbourhoodStation",
	EzCollection = "EzCollection",
	TH711EzCollection = "TH711EzCollection",
	MYCollectco = "MYCollectco",
}


export enum PriceType {
	All = "All",
	Free = "Free",
	NeedPay = "NeedPay",
}


export enum IconType {
	Car = "Car",
	Subway = "Subway",
	House = "House",
	EzCol = "EzCol",
}


export enum Week {
	Mon = "Mon",
	Tues = "Tues",
	Wed = "Wed",
	Thu = "Thu",
	Fri = "Fri",
	Sat = "Sat",
	Sun = "Sun",
}



export interface Result {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	code?: number;
	message?: string;
}

export interface CustomerAddress {
	/**
	 * @pattern ^\d+$
	 */
	customerAddressId?: string;
	isMajor?: boolean;
	zipcode?: string;
	address?: string;
	shipToName?: string;
	shipToPhone?: string;
	shipToAddress1?: string;
	shipToAddress2?: string;
	shipToState?: string;
	shipToCity?: string;
	buildingType?: string;
	block?: string;
	street?: string;
	floor?: string;
	unit?: string;
	buildingName?: string;
	destCode?: string;
	company?: string;
	district?: string;
	subDistrict?: string;
	/**
	 * @pattern ^\d+$
	 */
	createDate?: string;
	/**
	 * @pattern ^\d+$
	 */
	updateDate?: string;
	/**
	 * @pattern ^\d+$
	 */
	customerId?: string;
	fullAddress?: string;
}

export interface Warehouse {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	name?: string;
	code?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	floor?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	warehouse_type_id?: number;
	is_active?: boolean;
}

export interface WarehouseArea {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	name?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	region_id?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	floor?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	service_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shipment_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	delivery_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	product_category_id?: number;
	is_active?: boolean;
}

export interface WarehouseAreaView {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	name?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
	warehouse_name?: string;
	/**
	 * @pattern ^\d+$
	 */
	region_id?: string;
	region_code?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	floor?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	service_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shipment_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	delivery_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	product_category_id?: number;
	is_active?: boolean;
}

export interface Shelf {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_area_id?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shelf_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	package_type_id?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	position_x?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	position_y?: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	position_z?: number;
	is_active?: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shelf_group?: number;
}

export interface ShelfView {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
	warehouse_name?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_area_id?: string;
	warehouse_area_name?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shelf_type_id?: number;
	shelf_type_name?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	package_type_id?: number;
	is_active?: boolean;
}

export interface ShelfType {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	name?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	min_weight?: string;
	include_min?: boolean;
	/**
	 * @pattern ^\d+$
	 */
	max_weight?: string;
	include_max?: boolean;
	is_active?: boolean;
}

export interface Container {
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	release_date?: string;
	/**
	 * @pattern ^\d+$
	 */
	region_id?: string;
	shipment_type?: string;
	logistics_provider?: string;
	package_total_number?: string;
	package_total_weight?: string;
	package_total_volume_weight?: string;
	boxes?: ContainerPackingBox[];
	flights?: ContainerFlight[];
}

export interface ContainerFlight {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	container_code?: string;
	transport_code?: string;
	transport_code_color?: string;
	transit_transport_code?: string;
	transit_transport_code_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	begin_transport_date?: string;
	begin_transport_date_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	arrived_hub_date?: string;
	arrived_hub_date_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	leaving_hub_date?: string;
	leaving_hub_date_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	arrived_destination_date?: string;
	arrived_destination_date_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	leaving_customs_date?: string;
	/**
	 * @pattern ^\d+$
	 */
	arrived_warehouse_date?: string;
	arrived_warehouse_date_color?: string;
	/**
	 * @pattern ^\d+$
	 */
	eta_date?: string;
	memo?: string;
}

export interface ContainerPackingBox {
	container_code?: string;
	packing_box_code?: string;
}

export interface Package {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	code?: string;
	/**
	 * @pattern ^\d+$
	 */
	region_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	customer_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	platform_id?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	delivery_type_id?: number;
	/**
	 * @pattern ^\d+$
	 */
	delivery_station_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	charge_weight?: string;
	/**
	 * @pattern ^\d+$
	 */
	package_weight?: string;
	/**
	 * @pattern ^\d+$
	 */
	volume_weight?: string;
	/**
	 * @pattern ^\d+$
	 */
	eta_date?: string;
	express_code?: string;
	status?: PackageStatus;
	recipient?: Recipient;
}

export interface PackageStatus {
	/**
	 * @pattern ^\d+$
	 */
	package_id?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	package_status?: number;
}

export interface Recipient {
	name?: string;
	telephone?: string;
	zipcode?: string;
	address?: string;
}

export interface PackageTrack {
	/**
	 * @pattern ^\d+$
	 */
	package_id?: string;
	package_status?: string;
	package_track?: string;
	/**
	 * @pattern ^\d+$
	 */
	track_time?: string;
}

export interface PackageRemark {
	/**
	 * @pattern ^\d+$
	 */
	package_id?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	package_status?: number;
	package_remark?: string;
	/**
	 * @pattern ^\d+$
	 */
	remark_time?: string;
}

export interface PackageView {
	package?: Package;
	tracks?: PackageTrack[];
	remarks?: PackageRemark[];
}

export interface Timings {
	date_of_week?: string;
	/**
	 * @pattern ^\d+$
	 */
	start_time?: string;
	/**
	 * @pattern ^\d+$
	 */
	end_time?: string;
	/**
	 * @pattern ^\d+$
	 */
	cut_off?: string;
}

export interface TimingDisplay {
	dates?: string;
	timing?: string[];
}

export interface CutOffTimeValue {
	delivery_times?: string[];
	ahead_of_time?: string;
	is_today?: boolean;
}

export interface StationDetail {
	station_name?: string;
	station_subname?: string;
	station_address?: string;
	/**
	 * @pattern ^\d+$
	 */
	max_weight?: string;
	/**
	 * @minimum 0
	 */
	longtitude?: number;
	/**
	 * @minimum 0
	 */
	latitude?: number;
	station_image?: string;
	station_icon_image?: string;
	station_label?: string;
	timings?: Timings[];
	time_display?: TimingDisplay[];
	cut_offs?: string[];
	/**
	 * @pattern ^\d+$
	 */
	station_id?: string;
	period_time?: {[key: string]: CutOffTimeValue};
}

export interface StationInfo {
	delivery_type?: DeliveryType;
	station_name?: string;
	station_subname?: string;
	time_slot?: string;
	/**
	 * @minimum 0
	 */
	longtitude?: number;
	/**
	 * @minimum 0
	 */
	latitude?: number;
	/**
	 * @minimum 0
	 */
	distance?: number;
	distance_info?: string;
	fee?: string;
	/**
	 * @pattern ^\d+$
	 */
	max_weight?: string;
	overweight?: boolean;
	station_address?: string;
	/**
	 * @pattern ^\d+$
	 */
	station_id?: string;
	delivery_type_name?: string;
	delivery_type_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	region_id?: string;
	time_slot_display?: string[];
	/**
	 * @pattern ^\d+$
	 */
	arrangement_id?: string;
	icon_type?: IconType;
	originFee?: string;
	unAvailable?: boolean;
	unAvailableReason?: string;
	/**
	 * @pattern ^\d+$
	 */
	minWeight?: string;
	/**
	 * @pattern ^\d+$
	 */
	stationTypeID?: string;
	stationTypeCode?: string;
}

export interface SimpleStationInfo {
	/**
	 * @pattern ^\d+$
	 */
	station_id?: string;
	/**
	 * @minimum 0
	 */
	longtitude?: number;
	/**
	 * @minimum 0
	 */
	latitude?: number;
	overweight?: boolean;
	delivery_type?: DeliveryType;
	icon_type?: IconType;
	originFee?: string;
	fee?: string;
	unAvailable?: boolean;
	unAvailableReason?: string;
}

export interface Region {
	/**
	 * @pattern ^\d+$
	 */
	id?: string;
	/**
	 * @pattern ^\d+$
	 */
	parent_id?: string;
	region_name?: string;
	region_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	max_weight?: string;
	is_leaf?: boolean;
	is_active?: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	time_zone?: number;
	/**
	 * @pattern ^\d+$
	 */
	start_date?: string;
	/**
	 * @pattern ^\d+$
	 */
	end_date?: string;
	has_child?: boolean;
}

export interface ShortRegionInfo {
	name?: string;
	code?: string;
	subChilds?: ShortRegionInfo[];
}