/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */



export enum DeliveryType {
	Invalid = "Invalid",
	SelfCollection = "SelfCollection",
	NeighbourhoodStation = "NeighbourhoodStation",
	Subway = "Subway",
	Home = "Home",
	EzCollection = "EzCollection",
	TH711EzCollection = "TH711EzCollection",
	MYCollectco = "MYCollectco",
}