/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */



export interface Html {
	data?: string;
}

export interface GzipStream {
	/**
	 * @pattern ^\d+$
	 */
	handle?: string;
}