#!/usr/bin/env node
const findAntdModules = require("find-antd-modules");
const path = require("path");
const fse = require("fs-extra");

function resolve(p) {
	return path.resolve(__dirname, p);
}

const inputPath = [
	"../src/views",
].map(resolve);

const distPath = resolve("../config/antd.entry.js");

function renderContent(list) {
	const content = list.map(item => `"${item}"`).join(",");
	return `
	/*eslint-disable*/
	module.exports = [${content}];
`;
}

(async () => {
	const files = await findAntdModules(inputPath);
	try {
		fse.writeFile(distPath, renderContent(files), {
			encoding: "utf8"
		});
	} catch (e) {
		console.error(e);
	}
})();
