/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Empty as CommonEmpty } from "../common/empty";
import webapi from "../webapi";

export interface Category {
	/**
	 * @pattern ^\d+$
	 */
	cid?: string;
	category?: string;
	chinese_category?: string;
	english_category?: string;
	trade_category?: string;
	hs_code?: string;
}

export interface SetInvoicePrintedReq {
	/**
	 * @pattern ^\d+$
	 */
	invoice_id?: string;
	printed?: boolean;
}

export interface FetchCategoryReq {
	/**
	 * @pattern ^\d+$
	 */
	cid?: string[];
}

export interface FetchCategoryResp {
	items?: Category[];
}

export interface InvoiceSKU {
	/**
	 * @pattern ^\d+$
	 */
	invoice_sku_id?: string;
	goods_description?: string;
	chinese_category?: string;
	trade_category?: string;
	unit_type?: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	qty?: number;
	/**
	 * @pattern ^\d+$
	 */
	unit_value?: string;
	english_category?: string;
	hs_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	cid?: string;
	/**
	 * @pattern ^\d+$
	 */
	order_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	order_item_id?: string;
	externalProductName?: string;
	/**
	 * @pattern ^\d+$
	 */
	externalUnitPrice?: string;
}

export interface Invoice {
	/**
	 * @pattern ^\d+$
	 */
	invoice_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	shipment_type_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	logistics_provider_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	dispatch_provider_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	delivery_type_id?: string;
	nick_name?: string;
	package_code?: string;
	send_to?: string;
	send_zipcode?: string;
	send_phone?: string;
	send_address?: string;
	send_state?: string;
	from?: string;
	from_zipcode?: string;
	from_phone?: string;
	from_address?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
	origin_country_code?: string;
	destination_country_code?: string;
	skus?: InvoiceSKU[];
	/**
	 * @pattern ^\d+$
	 */
	total_value?: string;
	is_print?: boolean;
	is_pick_big?: boolean;
	/**
	 * @pattern ^\d+$
	 */
	pick_weight?: string;
	color_name?: string;
	color_value?: string;
	transport_number?: string;
	/**
	 * @pattern ^\d+$
	 */
	pickup_period_type_id?: string;
	ship_to_city_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	partyId?: string;
	isCod?: boolean;
	serviceType?: string;
	jneOriginBranchCode?: string;
	originCityCode?: string;
	destCode?: string;
	externalOrderNo?: string;
	shipmentTypeName?: string;
}

export interface CreateInvoiceReq {
	invoice?: Invoice;
}

export interface FetchInvoiceReq {
	package_code?: string;
}

export interface FetchInvoiceResp {
	invoice?: Invoice;
}

export interface FetchInvoiceByStockInReq {
	stockin_code?: string;
}

export interface FetchInvoiceByStockInResp {
	invoice?: Invoice;
}

export interface UpdateInvoiceReq {
	invoice?: Invoice;
}

export interface FetchInvoiceSKUsReq {
	/**
	 * @pattern ^\d+$
	 */
	invoice_id?: string;
}

export interface FetchInvoiceSKUsResp {
	skus?: InvoiceSKU[];
}

export interface UpdateInvoiceSKUReq {
	sku?: InvoiceSKU;
}

export interface AppendInvoiceSKUReq {
	sku?: InvoiceSKU;
	/**
	 * @pattern ^\d+$
	 */
	invoice_id?: string;
}

export interface AppendInvoiceSKUResp {
	/**
	 * @pattern ^\d+$
	 */
	invoice_sku_id?: string;
}

export interface RemoveInvoiceSKUReq {
	/**
	 * @pattern ^\d+$
	 */
	invoice_sku_id?: string;
}

export interface InvoiceTemplate {
	/**
	 * @pattern ^\d+$
	 */
	invoice_template_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	shipment_type_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	delivery_type_id?: string;
	origin_country_code?: string;
	destination_country_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	logistics_provider_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	dispatch_provider_id?: string;
	template?: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouse_id?: string;
}

export interface CreateInvoiceTemplateReq {
	template?: InvoiceTemplate;
}

export interface UpdateInvoiceTemplateReq {
	template?: InvoiceTemplate;
}

export interface SearchInvoiceTemplateReq {
	/**
	 * @pattern ^\d+$
	 */
	shipment_type_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	delivery_type_id?: string;
	origin_country_code?: string;
	destination_country_code?: string;
	/**
	 * @pattern ^\d+$
	 */
	logistics_provider_id?: string;
	/**
	 * @pattern ^\d+$
	 */
	dispatch_provider_id?: string;
}

export interface SearchInvoiceTemplateResp {
	templates?: InvoiceTemplate[];
}

export interface SaveInvoiceURLReq {
	packageCode?: string;
	invoiceURL?: string;
	wayBillURL?: string;
}

export interface RecordPackageDeliveryProviderReq {
	packageCode?: string;
	deliveryProvider?: string;
}



export function CreateInvoice(payload: Partial<CreateInvoiceReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/CreateInvoice", payload);
}

export function FetchInvoice(payload: Partial<FetchInvoiceReq>) {
	return webapi<FetchInvoiceResp>("chaplin.InvoiceService/FetchInvoice", payload);
}

export function FetchInvoiceByStockIn(payload: Partial<FetchInvoiceByStockInReq>) {
	return webapi<FetchInvoiceByStockInResp>("chaplin.InvoiceService/FetchInvoiceByStockIn", payload);
}

export function UpdateInvoice(payload: Partial<UpdateInvoiceReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/UpdateInvoice", payload);
}

export function FetchInvoiceSKUs(payload: Partial<FetchInvoiceSKUsReq>) {
	return webapi<FetchInvoiceSKUsResp>("chaplin.InvoiceService/FetchInvoiceSKUs", payload);
}

export function UpdateInvoiceSKU(payload: Partial<UpdateInvoiceSKUReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/UpdateInvoiceSKU", payload);
}

export function AppendInvoiceSKU(payload: Partial<AppendInvoiceSKUReq>) {
	return webapi<AppendInvoiceSKUResp>("chaplin.InvoiceService/AppendInvoiceSKU", payload);
}

export function RemoveInvoiceSKU(payload: Partial<RemoveInvoiceSKUReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/RemoveInvoiceSKU", payload);
}

export function SetInvoicePrinted(payload: Partial<SetInvoicePrintedReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/SetInvoicePrinted", payload);
}

export function FetchCategory(payload: Partial<FetchCategoryReq>) {
	return webapi<FetchCategoryResp>("chaplin.InvoiceService/FetchCategory", payload);
}

export function CreateInvoiceTemplate(payload: Partial<CreateInvoiceTemplateReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/CreateInvoiceTemplate", payload);
}

export function UpdateInvoiceTemplate(payload: Partial<UpdateInvoiceTemplateReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/UpdateInvoiceTemplate", payload);
}

export function SearchInvoiceTemplate(payload: Partial<SearchInvoiceTemplateReq>) {
	return webapi<SearchInvoiceTemplateResp>("chaplin.InvoiceService/SearchInvoiceTemplate", payload);
}

export function SaveInvoiceURL(payload: Partial<SaveInvoiceURLReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/SaveInvoiceURL", payload);
}

export function RecordPackageDeliveryProvider(payload: Partial<RecordPackageDeliveryProviderReq>) {
	return webapi<CommonEmpty>("chaplin.InvoiceService/RecordPackageDeliveryProvider", payload);
}


export default {
	CreateInvoice,
	FetchInvoice,
	FetchInvoiceByStockIn,
	UpdateInvoice,
	FetchInvoiceSKUs,
	UpdateInvoiceSKU,
	AppendInvoiceSKU,
	RemoveInvoiceSKU,
	SetInvoicePrinted,
	FetchCategory,
	CreateInvoiceTemplate,
	UpdateInvoiceTemplate,
	SearchInvoiceTemplate,
	SaveInvoiceURL,
	RecordPackageDeliveryProvider,
};