/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Empty as CommonEmpty } from "../common/empty";
import webapi from "../webapi";

export interface DeliveryToDetalaseReq {
	packageCode?: string;
}

export interface SyncBlueStatusReq {
	packageCode?: string;
}

export interface PurchaseOrderForcePushReq {
	/**
	 * @pattern ^\d+$
	 */
	orderId?: string;
}



export function DeliveryToDetalase(payload: Partial<DeliveryToDetalaseReq>) {
	return webapi<CommonEmpty>("ezShipOMS.Cronjob/DeliveryToDetalase", payload);
}

export function SyncBlueStatus(payload: Partial<SyncBlueStatusReq>) {
	return webapi<CommonEmpty>("ezShipOMS.Cronjob/SyncBlueStatus", payload);
}

export function AsyncBlueStatusJob(payload: Partial<CommonEmpty>) {
	return webapi<CommonEmpty>("ezShipOMS.Cronjob/AsyncBlueStatusJob", payload);
}

export function PurchaseOrderForcePush(payload: Partial<PurchaseOrderForcePushReq>) {
	return webapi<CommonEmpty>("ezShipOMS.Cronjob/PurchaseOrderForcePush", payload);
}


export default {
	DeliveryToDetalase,
	SyncBlueStatus,
	AsyncBlueStatusJob,
	PurchaseOrderForcePush,
};